### PR TITLE
feat(monk): make use of rf_active to detect monk scan for licenses

### PR DESCRIPTION
**Pull request by shaheemazmalmmd**
monk will scan license only when rf_acive is true
changes in license_ref table, Changed rf_active from false to true.
please do postinstall to test.

### CODE REVIEW

**Comment by max-wittig** [comment]
What does rf_active mean? If I understand this correctly this commit will improve performance by reducing scans of monk?

**Comment by shaheemazmalmmd** [comment]
rf_active refers to the status of license in license administration.

activestatuscapture

In this PR, monk scanner scans for the licenses with status active(yes/true).

**Comment by mcjaeger** [comment]
we have added this feature to pull off licenses from bulk scanning that are part of the server database. You need to keep them in the database for maintaining old results, however, for monk scanning they do not contribute to an optimal result.

Example BSD variant "France Telecom"

**Comment by max-wittig** [comment]
I'm just getting a 500 Error, when opening /repo
The /fo-postinstall script did ran
Maybe it conflicts with my existing uploads?

**Comment by shaheemazmalmmd** [comment]
Hi, i have tested this branch with existing uploads it works as expected. can you explain me how did you install this changes ??

**Comment by max-wittig** [comment]
It tried it again and it seems to work now. Weird.
Just testing the UI and checked the code. Looks good so far, but I don't know how to check what monk scans in detail

**Comment by mcjaeger** [comment]
some notes on the testing:
* just take some package with a full license text, i.e. an Apache 2.0 licensed package with license text on project root folder (commons-*, etc.)
* BEFORE deactivate in License Browser the Apache 2.0 license
* Upload and scan with Monk: Monk shall not find the Apache 2.0 license text.

**Comment by shaheemazmalmmd** [comment]
After seeing the error message i think that fossology is not able to get "businessrules.obligationmap" which is there in master but not in this branch. just do make clean and make install from root folder then  run fo-postinstall. i hope it should work

**Comment by max-wittig** [comment]
Monk doesn't start for me on your branch. I don't know why :/

**Comment by max-wittig** [comment]
Some questions:
If you understood this correctly

1. To disable an existing license you have to create a new license in `Admin-->License-Admin-->Add License` and set the concluded license to the license you want to disable?
2. How to remove user created licenses again?
3. Let's say you re-enable a license, but ran monk through the upload as this license was set to not active --> you can't schedule monk again on this upload

**Pull request merged**
