### PR TITLE
fix(delagent): Delete-Folder without deleting duplicate upload/s in o…

### PR DESCRIPTION
**Pull request by ag4ums**
…ther folders

### CODE REVIEW

**Comment by maxhbr** [comment]
The linter finds errors:

**Comment by maxhbr** [comment]
@anupam: please do not remove the changelog test from travis! If that test fails it might be useful to rebase on current master which might have changes in the changelog test configuration.

**Comment by ag4ums** [comment]
@maxhbr it was failing after rebase with current master(check this https://travis-ci.org/fossology/fossology/builds/282700942?utm_source=github_status&utm_medium=notification), quick check with @max-wittig found that sometime its breaking.

**Comment by mcjaeger** [comment]
what I tested on
```
Version: [3.1.0], Branch: [contrib/delete-folder-fix], Commit: [#fcb835] 2017/10/04 10:53 UTC built @ 2018/01/22 21:27 UTC
```
steps:
* upload some package
* create folder 111 and folder 222
* copy upload to folders 111 and 222
* delete uploaded file from 222
-> all uploads are away
@ag4ums please clarify how to test this feature.

**Comment by ag4ums** [comment]
@mcjaeger 
Currently, "Organize->folder->delete folder" option deletes that particular folder as well as the copied folder .
this PR restrict deletion of copied/original folder. 
Steps to test : 
  * create a folder A
  * upload some package under folder A
  * create a copy of the folder B
  * delete folder A
  * Folder B should not get deleted.

**Comment by mcjaeger** [comment]
@ag4ums I feel uncertain about the commit 
https://github.com/fossology/fossology/pull/905/commits/fcb83578eb2befd84eac38aff4cfc1d9a402d8b4
-> it seems to be on master already, could you pls rebase?

**Comment by ag4ums** [comment]
rebase done.

**Pull request merged**
