### PR TITLE
feat(organize): add upload datetime and status to move uploads page

### PR DESCRIPTION
**Pull request by max-wittig**
similar to "Upload to reuse"

### CODE REVIEW

**Comment by mcjaeger** [comment]
hi, please help with more description what it does and how to test it.

**Comment by max-wittig** [comment]
Attached screenshots show the changes, with the first image showing the current implementation of the 

Organize-->Uploads --> Move or Copy Page

and the second screenshot showing the changes made.

Upload-date and status was added for additional information, similar how it already is on the 
Upload --> From File --> Upload to Reuse Select Box at the bottom(3rd image)

move-copy-before

move-copy-after

image

**Comment by mcjaeger** [comment]
Hm, this is unfortunate. I think @shaheemazmalmmd has started working on a Javascript based table with sorting by table header click on this. we could merge this, but it will be replaced in future likely.

**Comment by max-wittig** [comment]
Oh okay. Sounds like a good improvement. Would merging this commit hinder @shaheemazmalmmd development of his replacement?

**Comment by max-wittig** [comment]
Any updates on the status of @shaheemazmalmmd replacement?

**Comment by shaheemazmalmmd** [comment]
Started a branch for this changes but not able to finish. i think we can merge this branch after the review and successful test

**Pull request merged**
