### PR TITLE
Revert "fix(testCases): Fix scheduler and ununpack test cases"

### PR DESCRIPTION
**Pull request by maxhbr**
The pullrequest fossology/fossology#1092 introduces multiple problems (see https://github.com/fossology/fossology/pull/1092#commitcomment-30133056 and  https://github.com/fossology/fossology/pull/1092#issuecomment-413890496)

Reverts fossology/fossology#1092

@robertvolkmann thanks for pointing the issues out.

### CODE REVIEW

**Comment by maxhbr** [comment]
Summaries of issues mentioned in the conversation of fossology/fossology#1092:

This PR
- elongates the execution times of from 2h30 - 3h30 to 4h45 - 5h30
- makes `make test` run the script `utils/prepare-test` which
  - **requires `sudo`**
  - calls `apt-get` to install dependencies
    - which is an **unexpected** side effect
    - which **only works on ubuntu / debain**
  - calls `chown $(whoami) /var/local/cache/fossology` and **breaks the current fossology instance**
  - creates the user `fossy` with password `fossy` in the db
    - this might change the password of `fossy` back to default which is a **potentially security risk** and **might break the current fossology instance**
  - creates a testuser in the current postgres which might be in productive use
  - writes two new lines to `~/.pgpass` on every run
- reactivates the blinking ftp test

**Comment by GMishx** [comment]
Instead of reverting the PR, what I suggest is
1.  To remove the `utils/prepare-test` from the `test` target. Let the user decide to run it or not.
2.  Deactivate the FTP test (again).
3.  Reduce the redundant PHP-GCC test cases.

By removing the redundant PHP-GCC test cases, we can bring down the test matrix from 22 tests to **11**.

**Comment by GMishx** [comment]
Okay, agree. Will add the warning message as well.

**Comment by GMishx** [comment]
Please check #1173

**Comment by maxhbr** [comment]
obsolete due to #1173

**Pull request closed without merging**
