### PR TITLE
feat(copyright): save deleted copyrights in copyright_event table

### PR DESCRIPTION
**Pull request by shaheemazmalmmd**
## Description

Separate copyright, author, ecc and keyword edits to another "tableName_event" table. for better reuse.  

### Changes

* Script to migrate old data.
* Create new _event table.
* Changes to save new data in new event table.

## How to test

* End-to-end testing of copyright and sister tables with reuse.

### CODE REVIEW

**Review by GMishx — CHANGES_REQUESTED** [review]

**Comment by GMishx** [comment]
Normal copyright edit/deactivation/activation seems to work fine but there are some glitches
1. I can not deactivate any entry in ECC and Keyword tables. Only Copyright and Email/Author table works.
2. When reusing an upload with "Reuse deactivated copyright", the number of copyrights increase slightly in the new upload and this happened in the old upload:

image

The count of each deactivated copyright just doubled. But if I click on the link to see the files, I get the correct results:
image

3. I made some edits in the copyrights and generated the report. One of the copyright (from Ayush) is missing from report:
    image
    image

**Comment by mcjaeger** [comment]
tried to test it,but updating from a version 3.7 does not seem to work

```
fossy@fossytest:~/fossy-siemens/fossology$ sudo /usr/local/lib/fossology/fo-postinstall
...
*** Instance UUID ***PHP Warning:  pg_query(): Query failed: ERROR:  permission denied to create extension "uuid-ossp"
HINT:  Must be superuser to create this extension. in /usr/local/share/fossology/lib/php/Db/Driver/Postgres.php on line 79
[2021-04-06 13:23:33] /usr/local/share/fossology/lib/php/libschema.php.CRITICAL: ERROR:  permission denied to create extension "uuid-ossp" HINT:  Must be superuser to create this extension. [] []
PHP Fatal error:  Uncaught Fossology\Lib\Exception: error executing: 
BEGIN;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TABLE IF NOT EXISTS instance (
    id bool PRIMARY KEY DEFAULT TRUE,
    instance_uuid UUID NOT NULL DEFAULT uuid_generate_v4(),
CONSTRAINT tbl_id_uni CHECK (id));
COMMIT;
     

ERROR:  permission denied to create extension "uuid-ossp"
HINT:  Must be superuser to create this extension. in /usr/local/share/fossology/lib/php/Db/DbManager.php:144
Stack trace:
#0 /usr/local/share/fossology/lib/php/Db/DbManager.php(203): Fossology\Lib\Db\DbManager->checkResult(false, '\nBEGIN;\nCREATE ...')
#1 /usr/local/lib/fossology/instance_uuid.php(34): Fossology\Lib\Db\DbManager->queryOnce('\nBEGIN;\nCREATE ...')
#2 /usr/local/lib/fossology/instance_uuid.php(55): CreateInstanceUUIDTable(Object(Fossology\Lib\Db\ModernDbManager))
#3 /usr/local/lib/fossology/fossinit.php(404): require_once('/usr/local/lib/...')
#4 {main}
  thrown in /usr/local/share/fossology/lib/php/Db/DbManager.php on line 144
fossy@fossytest:~/fossy-siemens/fossology$ 
```

**Comment by mcjaeger** [comment]
> tried to test it,but updating from a version 3.7 does not seem to work
> 
> ```
> fossy@fossytest:~/fossy-siemens/fossology$ sudo /usr/local/lib/fossology/fo-postinstall
> ...
> *** Instance UUID ***PHP Warning:  pg_query(): Query failed: ERROR:  permission denied to create extension "uuid-ossp"
> HINT:  Must be superuser to create this extension. in /usr/local/share/fossology/lib/php/Db/Driver/Postgres.php on line 79
> [2021-04-06 13:23:33] /usr/local/share/fossology/lib/php/libschema.php.CRITICAL: ERROR:  permission denied to create extension "uuid-ossp" HINT:  Must be superuser to create this extension. [] []
> PHP Fatal error:  Uncaught Fossology\Lib\Exception: error executing: 
> BEGIN;
> CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
> CREATE TABLE IF NOT EXISTS instance (
>     id bool PRIMARY KEY DEFAULT TRUE,
>     instance_uuid UUID NOT NULL DEFAULT uuid_generate_v4(),
> CONSTRAINT tbl_id_uni CHECK (id));
> COMMIT;
>      
> 
> ERROR:  permission denied to create extension "uuid-ossp"
> HINT:  Must be superuser to create this extension. in /usr/local/share/fossology/lib/php/Db/DbManager.php:144
> Stack trace:
> #0 /usr/local/share/fossology/lib/php/Db/DbManager.php(203): Fossology\Lib\Db\DbManager->checkResult(false, '\nBEGIN;\nCREATE ...')
> #1 /usr/local/lib/fossology/instance_uuid.php(34): Fossology\Lib\Db\DbManager->queryOnce('\nBEGIN;\nCREATE ...')
> #2 /usr/local/lib/fossology/instance_uuid.php(55): CreateInstanceUUIDTable(Object(Fossology\Lib\Db\ModernDbManager))
> #3 /usr/local/lib/fossology/fossinit.php(404): require_once('/usr/local/lib/...')
> #4 {main}
>   thrown in /usr/local/share/fossology/lib/php/Db/DbManager.php on line 144
> fossy@fossytest:~/fossy-siemens/fossology$ 
> ```

well, `ALTER USER fossy WITH SUPERUSER; ` also does the trick, but is maybe not desired at update tests from previous versions.

**Comment by mcjaeger** [comment]
unffortunately, it ides not work. Attached a readme oss for time-1.9 created with Fossology 3.7:

[ReadMe_OSS_time-1.9.tar.gz_1617711866.txt](https://github.com/fossology/fossology/files/6266470/ReadMe_OSS_time-1.9.tar.gz_1617711866.txt)

(89 nice and clean copyrights)

Then, generating and downloading the same Readme OSS with the updated fossology from branch `contrib/copyrightEvent`:

[ReadMe_OSS_time-1.9.tar.gz_1617729697.txt](https://github.com/fossology/fossology/files/6266487/ReadMe_OSS_time-1.9.tar.gz_1617729697.txt)

-> a big mess. even noting was done on the upload, just after the upgrade and modification of the DB. DB update looks like the fowlloing BTW. 

```
Old release was 3.3.0
  Applying database functions
DB schema has been updated for fossology.
Database schema update completed successfully.
Update reference licenses
*** Instance UUID ***INSTANCE UUID Empty - creating...
INSTANCE UUID: a9eea434-8267-4290-951e-0410f8846661
*** Recoding 997 records to UTF-8. ***
*** Recoding entries in copyright and sister tables ***
*** Recoding 299 records from copyright table ***
*** Recoded 0 for copyright table ***
*** Recoding 589 records from author table ***
*** Recoded 0 for author table ***
*** Recoding 4 records from ecc table ***
*** Recoded 0 for ecc table ***
*** Recoding 105 records from keyword table ***
*** Recoded 0 for keyword table ***
*** Inserting 118 records from copyright to copyright_event table ***
Inserted 118 out of 118 rows in copyright_event table

Database connectivity is good.
*** Setting up scheduler ***
*** Setting up the web interface ***
NOTE: Adding user www-data to group fossy
NOTE: enabling fossology site for apache2
Enabling site fossology.
To activate the new configuration, you need to run:
  systemctl reload apache2
[ ok ] Reloading apache2 configuration (via systemctl): apache2.service.
NOTE: Restart apache to apply the changes
FOSSology postinstall complete, but sure to complete the remaining
  steps in the INSTALL instructions.

```

**Comment by mcjaeger** [comment]
cool! tested again with clean 3.7
* first upload copyright cleaning
* second upload reuse all from first upload
* install 3.9
* download reports: all good.

**Review by mcjaeger — APPROVED** [review]
cool! tested again after update with clean 3.7
* first upload copyright cleaning
* second upload reuse all from first upload
* install 3.9
* download reports: all good.

**Comment by mcjaeger** [comment]
(unified report and spdx looks also good)

**Pull request merged**
