### PR TITLE
feat(copyright&ecc): Add multi delete option to copyright and ecc

### PR DESCRIPTION
**Pull request by shaheemazmalmmd**
please execute fo-postinstall for running this pull request code properly

### CODE REVIEW

**Comment by max-wittig** [comment]
Your code doesn't work for me. I uploaded 'fossI16L518.7z' and checked all the boxes for "optional analysis" and "Automatic Concluded License Decider".
Now, when I open the ECC page I just get `You are not logged in. Go to login page?`
and this error in the browser console `http://127.0.0.1/repo/?mod=ajax-copyright-hist&action=getData&sEcho=1&iColu…false&bSortable_3=false&upload=140&item=30700&agent=58&type=ecc&filter=all`

**Comment by shaheemazmalmmd** [comment]
Hi @max-wittig 

Thank you for testing this issue.

I have followed the same procedure explained in the above comment, But not able to reproduce the issue. can you please provide some more information.

Uploaded 'fossI16L518.7z' with all checked boxes for "optional analysis" and "Automatic Concluded License Decider"

screenshot1

And click on the ECC 

screenshot2


Please provide some more information. To reproduce and fix 


Thank You

**Comment by max-wittig** [comment]
I'm not able to get XDebug to connect so I can't really provide much more information.
I just clicked on the blue link in the `Browse` Window and they ECC
image

**Comment by max-wittig** [comment]
Also you should change your commit notes style. Instead of "Added" use the present tense for commit messages, body and footer content.  "Add multi delete option to copyright and ecc"
Thanks

**Comment by max-wittig** [comment]
I tried your PR again, but this time I ran the postinstall script again.
This solved it. Could you add this to your PR description please?

**Comment by mcjaeger** [comment]
@max-wittig  so test for this PR is successful? you are not clear on this.

**Comment by max-wittig** [comment]
You're right. It's not that important. Just that he knows for the future.
Yes it works for me, after running the postinstall script again

**Comment by mcjaeger** [comment]
@max-wittig do you also think the source code is OK? (from the conversation it seems to me that you have tested functionality)

**Comment by max-wittig** [comment]
Sorry Michael you're right. I just tested functionality before. Code is checked now. Looks good

**Pull request merged**
