### PR TITLE
feat(api): migrate `/tokens` endpoints to v2

### PR DESCRIPTION
**Pull request by GMishx**
## Description

Create a new `openapiv2.yaml` file to store the v2 related changes.
The idea is to keep using this file to store the changes related to only v2 migration like camelCasing changes, moving parameters from header to query, etc. Other changes like adding new endpoint need to be updated in both `openapi.yaml` and `openapiv2.yaml`.
Once every endpoint is migrated, the original file `openapi.yaml` can be replaced with this. This will allow to let everyone know v1 is deprecated from that point of time and v2 can be released with version `2.0.0`.

Update the `TokenRequest` component to use camelCasing and update endpoints accordingly.

## !Breaking
Remove the deprecated `/version` endpoint.

### Changes

1. Update `TokenRequest` component to use camelCasing.
2. Create new file `openapiv2.yaml`.
3. Remove deprecated `/version` endpoint.

## How to test

Test the `GET /api/tokens` and `POST /users/tokens` endpoints with both V1 and V2 to see if they are working as expected.

/cc @dushimsam

### CODE REVIEW

**Comment by GMishx** [comment]
/cc @deveaud-m @shaheemazmalmmd 

Does this strategy of migration from v1 to v2 makes sense or shall we look for an alternative?

**Comment by dushsam2** [comment]
> /cc @deveaud-m @shaheemazmalmmd
> 
> Does this strategy of migration from v1 to v2 makes sense or shall we look for an alternative?

Thanks for introducing this change @GMishx I had been wondering how we can handle the two versions in the same file.

**Comment by dushimsam** [comment]
Thanks for introducing this change @GMishx . I was also looking for a way to handle the two versions in the same file, but this is a better and more efficient solution.

**Comment by shaheemazmalmmd** [comment]
> /cc @deveaud-m @shaheemazmalmmd
> 
> Does this strategy of migration from v1 to v2 makes sense or shall we look for an alternative?

Perfect. Idea looks great to me.

**Pull request merged**
