### PR TITLE
fix(ninka): ninka needs a new dependency

### PR DESCRIPTION
**Pull request by maximilianhuber**

### CODE REVIEW

**Comment by maximilianhuber** [comment]
This is an alternative to https://github.com/fossology/fossology/pull/798

**Comment by max-wittig** [comment]
Isn't this an addition to PR #798, rather than an alternative? Travis is still failing with this commit alone, because travis ci tests are fixed in PR #798

**Comment by maximilianhuber** [comment]
Sorry, i thought that travis already uses the `install-ninka.sh` script. should now be fixed.

**Comment by max-wittig** [comment]
Travis tests fail, because ninka changed. Should we remove them or modify the values that are expected?
<pre>1) MonkBulkTest::testRunMonkBulkScanWithMultipleLicenses
Failed asserting that 5 matches expected 6.
/home/travis/build/fossology/fossology/src/monk/agent_tests/Functional/bulkTest.php:293</pre>

**Comment by maximilianhuber** [comment]
This is a randomly failing test due to a race condition. One should fix that. There should already be an issue for that.

**Comment by max-wittig** [comment]
Ah okay sorry.

**Comment by maximilianhuber** [comment]
No problem.

**Comment by maximilianhuber** [comment]
See: https://github.com/fossology/fossology/issues/650

**Pull request merged**
