### PR TITLE
feat(api): Upgrade Search, Copyright & Admin APIs to Version 2

### PR DESCRIPTION
**Pull request by dvjsharma**
## Description

This PR aims to upgrade the `/search` , `/copyright`  and `/admin` endpoints to v2 in accordance with the new upgrade guidelines.

### Changes

* Updated `/search` GET, `/uploads/{id}/item/{itemId}/{xx}` GET, `/customise` GET endpoints.
* Updated `openapiv2.yaml` to have all documentation changes.

### How to Test

* Open the `openapiv2.yaml` file in Swagger Editor and test all the updated endpoints for v2 specific responses. All function as intended.
* Execute unit tests, all pass without any issues.

CC @GMishx @shaheemazmalmmd @dushimsam

### CODE REVIEW

**Comment by soham4abc** [comment]
@shaheemazmalmmd @GMishx @dushimsam 

Working as per expectation.

Please do provide your reviews

**Review by dushimsam — APPROVED** [review]
LTGM

**Comment by dushimsam** [comment]
@dvjsharma  why is the branch named as `patch-one` ?

**Comment by dvjsharma** [comment]
I usually include issue numbers in branch names. However, I did not open a new one to track this, hence the name. Let me know if I should change it @dushimsam.

**Pull request merged**
