### PR TITLE
feat(api): add fossology REST api

### PR DESCRIPTION
**Pull request by GMishx**
Continuation of #837

## FOSSology REST OpenAPI specification:
Can be viewed in rendered form on http://editor2.swagger.io/

**Implemented**:

| Request | API |
| --- | --- |
| GET       | /repo/api/v1/auth/ |
| GET       | /repo/api/v1/uploads/{id} |
| DELETE | /repo/api/v1/uploads/{id} |
| PATCH   | /repo/api/v1/uploads/{id} |
| PUT       | /repo/api/v1/uploads/{id} |
| GET       | /repo/api/v1/uploads/ |
| GET       | /repo/api/v1/search/ |
| GET       | /repo/api/v1/users/ |
| GET       | /repo/api/v1/users/{id} |
| DELETE | /repo/api/v1/users/{id} |
| GET       | /repo/api/v1/jobs/ |
| GET       | /repo/api/v1/jobs/{id} |
| POST     | /repo/api/v1/jobs/ |

The user can get the required authentication header by calling:
`/repo/api/v1/auth/?username=<username>&password=<password>`

### Steps to create HTML from Swagger YAML
1. Install [pretty-swag](https://github.com/twskj/pretty-swag#installation).
1. Change the `host` and `schema` in `src/www/ui/api/documentation/openapi.yaml` to match current implementation.
1. Generate the HTML:
    ```bash
    pretty-swag -i path/to/openapi.yaml -c path/to/pretty-swag.json -o path/to/output.html
    ```
1. Host the HTML

Sample (with host as HTML): https://gmishx.github.io/fossologyrest/output.html

### CODE REVIEW

**Comment by max-wittig** [comment]
Authorization works by using 
```
http://127.0.0.1:8081/repo/api/v1/auth/?username=fossy&password=fossy
{"header":"authorization: Basic Zm9zc3k6Zm9zc3k="}
```

but not without the slash, which I find a bit confusing as user
```
http://127.0.0.1:8081/repo/api/v1/auth?username=fossy&password=fossy
{"code":403,"message":"Not authorized","type":"ERROR"}
```

**Comment by max-wittig** [comment]
I would also suggest to use the standard bearer authorization header.

Instead of using 
```
authorization: Basic Zm9zc3k6Zm9zc3k=
```

maybe this could be used instead:

```
Authorization: Bearer Zm9zc3k6Zm9zc3k=
```

See: https://swagger.io/docs/specification/authentication/bearer-authentication/

**Comment by GMishx** [comment]
Thanks for your suggestion @max-wittig, I am planning to implement Bearer authentication in version 2 (#1214).

**Comment by GMishx** [comment]
The forward slash is an issue Silex. It can be removed specifically for the `/auth/` if it will serve the purpose?

**Comment by max-wittig** [comment]
@GMishx Ideally both should be accepted by the API. 
But isn't it already Bearer Auth? Just the names of the header is different.

**Comment by GMishx** [comment]
1. Silex does not support regex in routes so only one of `/auth` and `/auth/` can be implemented here.

2. For authentication
    >  Basic authentication is a simple authentication scheme built into the HTTP protocol. The client sends HTTP requests with the Authorization header that contains the word Basic word followed by a space and a base64-encoded string username:password.

    So the `Zm9zc3k6Zm9zc3k=` in your message is basically your `base64(username:password)` and not a token.

    >  Bearer authentication (also called token authentication) is an HTTP authentication scheme that involves security tokens called bearer tokens.

    This need to be implemented separately. So I will do in next PR.

**Comment by GMishx** [comment]
They are fixed here: https://github.com/fossology/fossology/pull/1214

**Comment by hieupvtsdv** [comment]
Have Error when i run command:
`pretty-swag -i path/to/openapi.yaml -c path/to/pretty-swag.json -o path/to/output.html`
Log:
`Error: TypeError: Cannot convert undefined or null to object` 
Please help me fix this bug.

**Comment by maxhbr** [comment]
This does not look like actual paths. Please add actual paths and more details.

And please do not comment on closed PRs, but instead create a new issue!

**Comment by GMishx** [comment]
Hello @hieupvtsdv,

As @maxhbr suggested, it is a good idea to open a new issue for this.

But to answer your query quickly, FOSSology moved to OpenAPI Specification v3 and pretty-swag currently does not support it. Check this [PR on pretty-swag](https://github.com/twskj/pretty-swag/pull/62) for more info.

**Pull request merged**
