### PR TITLE
fix(PSR-12): closing ?> tag MUST be omitted

### PR DESCRIPTION
**Pull request by vargenau**
## Description

PSR-12:

All PHP files MUST end with a non-blank line, terminated with a single LF.

The closing ?> tag MUST be omitted from files containing only PHP.

### Changes

Remove closing ?> tag

### CODE REVIEW

**Review by GMishx — APPROVED** [review]
LGTM

**Comment by GMishx** [comment]
@vargenau Thank you for the contribution.
Can you please squash the 2 commits into 1 so we can merge this branch?

**Comment by GMishx** [comment]
Hey @vargenau , looks like you've merged with master branch instead.

Please use `git rebase -i master` to rebase interactively and then squash the commits.

**Comment by vargenau** [comment]
Sorry, I created a mess when tying to squash.

I have created a new pull request #2599

Let us close this one.

**Comment by GMishx** [comment]
Merged #2599, thus closing this PR.

**Pull request closed without merging**
