### PR TITLE
feat(licenses): Apache detection code restructured. Apache and AGPL n…

### PR DESCRIPTION
**Pull request by rlintu**
## Description

Apache detection code restructured. Apache and AGPL naming unified. Bug fixes.

### Changes

Apache license detection was done in several places. Now the code is clarified and Apache license is mainly detected in `aslVersion` function.
Apache license was referred as `APACHE` or `ASL`. Now only `Apache` term is used.
AGPL license was rererred as `AGPL` or `AFFERO`. Now only `AGPL` term is used.

## How to test
nomos regression tests.

### CODE REVIEW

**Comment by mcjaeger** [comment]
unfortunately, first time with this branch nomos  at commit `Branch: [nomos-1903], Commit: [#45e654] 2019/03/21 09:01 UTC built @ 2019/04/21 21:42 UTC` crashes with scanning

https://github.com/spdx/license-list-data

geeky agent details look like this:

Screen Shot 2019-04-22 at 00 00 36

then, second time it crashed the same way, but different count of processed files:

Screen Shot 2019-04-22 at 10 00 52

total picture is like this. The SPDX test package has been used many times before ...

job file count:

Screen Shot 2019-04-22 at 10 02 37

**Comment by mcjaeger** [comment]
@shaheemazmalmmd like I should check the comments or rlintu? The question for me is if that is an error brought by the branch or is maybe in because of something different ...

**Comment by shaheemazmalmmd** [comment]
@mcjaeger : I have tested this scenario with current master. i can see the issue there as well. 
We can open a issue for NOMOS failure..

**Comment by mcjaeger** [comment]
@shaheemazmalmmd I have opened https://github.com/fossology/fossology/issues/1337 would you be Ok to merge this PR then?

**Pull request merged**
