### PR TITLE
test(api): added more test cases for upload,folder,license and group APIs

### PR DESCRIPTION
**Pull request by valens200**
## Description
This pull request  introduces more unit test cases for upload, folder, license and group APIs as reported in issue [#2755](https://github.com/fossology/fossology/issues/2755).

## Changes
This pull request maintains the currently available unit tests and introduces new ones in upload, folder, license and group APIs.

### CODE REVIEW

**Comment by dushsam2** [comment]
Can we squash the commits into 1

**Comment by dushimsam** [comment]
Can we squash these commits into 1

**Comment by valens200** [comment]
> Can we squash these commits into 1



> Can we squash these commits into 1

Yes please, you can do that while merging.

**Comment by valens200** [comment]
> > Can we squash these commits into 1
> 
> > Can we squash these commits into 1
> 
> Yes please, you can do that while merging.

**Pull request closed without merging**
