### PR TITLE
refactor(php):used expressions with combined operators

### LINKED ISSUE #2121: Increase the usage of expressions with combined operators
### Description
:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of combined operators](https://www.php.net/manual/en/language.operators.assignment.php#language.operators.assignment.arithmetic "Description for assignment operators") accordingly.

### Change suggestion
```diff
diff --git a/install/db/dbmigrate_3.5-3.6.php b/install/db/dbmigrate_3.5-3.6.php
index 3f754f95a..1cc373bbc 100644
--- a/install/db/dbmigrate_3.5-3.6.php
+++ b/install/db/dbmigrate_3.5-3.6.php
@@ -134,7 +134,7 @@ function updateHash($dbManager, $tableName)
     $dbManager->queryOnce($sql, __METHOD__ . ".update.$tableName.hash");
     $dbManager->commit();
 
-    $totalCount = $totalCount + $numberOfRecords;
+    $totalCount += $numberOfRecords;
     $numberOfRecords = calculateNumberOfRecordsToBeProcessed($dbManager, $tableName, "hash");
     $numberOfRecords = $numberOfRecords[0];
   }
@@ -193,7 +193,7 @@ function updateSHA256($dbManager, $tableName)
     $dbManager->queryOnce($sql, __METHOD__ . ".updatePfile_SHA256");
     $dbManager->commit();
 
-    $totalCount = $totalCount + $numberOfRecords;
+    $totalCount += $numberOfRecords;
     echo "* $totalCount pfile records updated *\n";
 
     $records = calculateNumberOfRecordsToBeProcessed($dbManager, $tableName, $tableName."_sha256");
diff --git a/install/db/dbmigrate_copyright-event.php b/install/db/dbmigrate_copyright-event.php
index 9ac75bde1..ac38039fd 100644
--- a/install/db/dbmigrate_copyright-event.php
+++ b/install/db/dbmigrate_copyright-event.php
@@ -102,7 +102,7 @@ function insertDataInToEventTables($dbManager)
       } else {
         $i = $j;
       }
-      $j = $j + MAX_SIZE_OF_ROW;
+      $j += MAX_SIZE_OF_ROW;
       $dbManager->commit();
       $endTime = microtime(true);
       $totalTime = ($endTime - $startTime);
diff --git a/src/cli/fo_antelink.php b/src/cli/fo_antelink.php
index 18925f817..1187037eb 100755
--- a/src/cli/fo_antelink.php
+++ b/src/cli/fo_antelink.php
@@ -407,7 +407,7 @@ function writeacme_project($project, $Verbose)
    * Watch out for time stamps in milliseconds
    */
   if ($projectDate > 20000000000) {
-    $projectDate = $projectDate / 1000; // convert to seconds if necessary
+    $projectDate /= 1000; // convert to seconds if necessary
   }
   $releasedate = date("Ymd", $projectDate);
 
diff --git a/src/delagent/agent_tests/Functional/ft_cliDelagentTest.php b/src/delagent/agent_tests/Functional/ft_cliDelagentTest.php
index 55a3aaf0a..93cda5d15 100644
--- a/src/delagent/agent_tests/Functional/ft_cliDelagentTest.php
+++ b/src/delagent/agent_tests/Functional/ft_cliDelagentTest.php
@@ -61,7 +61,7 @@ class ft_cliDelagentTest extends \PHPUnit\Framework\TestCase {
       $message = 'FATAL: cannot find executable file, stop testing\n');
     }
     // run it
-    $EXE_PATH = $EXE_PATH." -c $DB_CONF";
+    $EXE_PATH .=" -c $DB_CONF";
     $last = exec("$EXE_PATH -h 2>&1", $out, $rtn);
     $this->assertEquals($usage, $out[0]); // check if executable file delagent is exited
     $this->assertEquals($usageL, $out[6]); // check if the option -L removed
diff --git a/src/mimetype/agent_tests/Functional/cliParamsTest4Mimetype.php b/src/mimetype/agent_tests/Functional/cliParamsTest4Mimetype.php
index 0d8bf7fc5..b57052d5c 100644
--- a/src/mimetype/agent_tests/Functional/cliParamsTest4Mimetype.php
+++ b/src/mimetype/agent_tests/Functional/cliParamsTest4Mimetype.php
@@ -84,7 +84,7 @@ class cliParamsTest4Mimetype extends \PHPUnit\Framework\TestCase {
       $message = 'FATAL: cannot find executable file, stop testing\n');
     }
     // run it
-    $EXE_PATH = $EXE_PATH." -C -c $DB_CONF";
+    $EXE_PATH .=" -C -c $DB_CONF";
     $last = exec("$EXE_PATH -h 2>&1", $out, $rtn);
     $this->assertEquals($usage, $out[0]); // check if executable file mimetype is exited
   }
diff --git a/src/nomos/agent_tests/testdata/NomosTestfiles/Unlicense/bitcoin.php b/src/nomos/agent_tests/testdata/NomosTestfiles/Unlicense/bitcoin.php
index f76421414..2e59ee747 100644
--- a/src/nomos/agent_tests/testdata/NomosTestfiles/Unlicense/bitcoin.php
+++ b/src/nomos/agent_tests/testdata/NomosTestfiles/Unlicense/bitcoin.php
@@ -63,7 +63,7 @@ class Bitcoin {
       $dv = (string) bcdiv($dec, "16", 0);
       $rem = (integer) bcmod($dec, "16");
       $dec = $dv;
-      $return = $return . self::$hexchars[$rem];
+      $return .= self::$hexchars[$rem];
     }
     return strrev($return);
   }
@@ -118,7 +118,7 @@ class Bitcoin {
       $dv = (string) bcdiv($hex, "58", 0);
       $rem = (integer) bcmod($hex, "58");
       $hex = $dv;
-      $return = $return . self::$base58chars[$rem];
+      $return .= self::$base58chars[$rem];
     }
     $return = strrev($return);
 
diff --git a/src/spdx2/agent/spdx2.php b/src/spdx2/agent/spdx2.php
index 058f8201b..0fd2cbe1b 100644
--- a/src/spdx2/agent/spdx2.php
+++ b/src/spdx2/agent/spdx2.php
@@ -240,7 +240,7 @@ class SpdxTwoAgent extends Agent
       case "spdx2tv":
         break;
       case "dep5":
-        $prefix = $prefix . "copyright-";
+        $prefix .= "copyright-";
         break;
     }
     return $prefix . $partname . $postfix;
@@ -259,13 +259,13 @@ class SpdxTwoAgent extends Agent
       $fileName = strtoupper($this->outputFormat)."_".$packageName.'_'.time();
       switch ($this->outputFormat) {
         case "spdx2":
-          $fileName = $fileName ."-spdx.rdf";
+          $fileName .="-spdx.rdf";
           break;
         case "spdx2tv":
-          $fileName = $fileName .".spdx";
+          $fileName .=".spdx";
           break;
         case "dep5":
-          $fileName = $fileName .".txt";
+          $fileName .=".txt";
           break;
       }
       $this->filebasename = $fileName;
diff --git a/src/testing/dataFiles/mailTo.php b/src/testing/dataFiles/mailTo.php
index 3ff3a51c5..17884d511 100644
--- a/src/testing/dataFiles/mailTo.php
+++ b/src/testing/dataFiles/mailTo.php
@@ -32,5 +32,5 @@ $mailTo = "mark.donohoe@hp.com mary.laser@hp.com ";
 $others = "bob.gobeille@hp.com dong.ma@hp.com alex.dav.norton@hp.com  yao-bin.shi@hp.com";
 
 // the whole team, comment out as needed
-$mailTo = $mailTo . $others;
+$mailTo .= $others;
 ?>
\ No newline at end of file
diff --git a/src/wget_agent/agent_tests/Functional/cliParamsTest4WgetAgent.php b/src/wget_agent/agent_tests/Functional/cliParamsTest4WgetAgent.php
index caa6f01c6..b4f0cda06 100644
--- a/src/wget_agent/agent_tests/Functional/cliParamsTest4WgetAgent.php
+++ b/src/wget_agent/agent_tests/Functional/cliParamsTest4WgetAgent.php
@@ -72,7 +72,7 @@ class cliParamsTest4Wget extends \PHPUnit\Framework\TestCase {
       $message = 'FATAL: cannot find executable file, stop testing\n');
     }
     // run it
-    $WGET_PATH = $WGET_PATH." -C -c $db_conf";
+    $WGET_PATH .=" -C -c $db_conf";
     $last = exec("$WGET_PATH -h 2>&1", $out, $rtn);
     $this->assertEquals($usage, $out[0]); // check if executable file wget_agent is exited
   }
```

### PR DESCRIPTION
**Pull request by Ibrahim-Muhammad13**
## Description
Increase the usage of expressions with combined operators
this closes #2121

### CODE REVIEW

**Comment by Ibrahim-Muhammad13** [comment]
@GMishx  what can i do to get this merged?

**Comment by shaheemazmalmmd** [comment]
@Ibrahim-Muhammad13 Please rebase the branch with master also consider changing the commit message as per https://github.com/fossology/fossology/blob/master/CHANGELOG.md

**Comment by Ibrahim-Muhammad13** [comment]
@shaheemazmalmmd i think i fixed the conflicts and passed tests but i don't know what to edit in the commit message i did it as explained in contribution guide

**Comment by shaheemazmalmmd** [comment]
@Ibrahim-Muhammad13 I see that you have merged instead of rebase ? because of that morethan 200 commits got added to this PR. please have a look.

**Comment by GMishx** [comment]
@Ibrahim-Muhammad13 can you please update the PR for us to merge it?

**Comment by GMishx** [comment]
Merged in 7aa37b778158ef04d481bcc7dc3149f740194cdc

**Pull request closed without merging**
