### PR TITLE
fix(ui): add line break in upload name if exceeds 20 chars

### PR DESCRIPTION
**Pull request by shaheemazmalmmd**
## Description

add line break in upload name if exceeds 20 chars.

### Changes

* browse page
* single file view page.
* conf page
* info page

## How to test

* Upload a component with large name.
* Assign to a user with large username.
* check the scroll in single file view.

### CODE REVIEW

**Comment by ag4ums** [comment]
folder alignment need some correction

**Comment by GMishx** [comment]
> folder alignment need some correction

I have fixed it and pushed the commit. Can you please have a look again?

**Comment by ag4ums** [comment]
Bulk-license selection not happening due to pointer-events value

image

**Comment by GMishx** [comment]
> Bulk-license selection not happening due to pointer-events value

@ag4ums Can you please be more specific about "Selection not happening"? Does it mean you can not select text from background?
Because the `pointer-events: none` is added explicitly to allow the selection of text from background of bulk modal.

**Comment by GMishx** [comment]
Fixed @ag4ums please have a look

image

**Review by ag4ums — APPROVED** [review]
Code looks good, working as expected

**Pull request merged**
