### PR TITLE
.travis.yml: introduce matrix build, add QA and make test

### PR DESCRIPTION
**Pull request by bufferoverflow**
- add composer install
- create db and ~/.pgpass

### CODE REVIEW

**Comment by bobgob** [comment]
Will merge when conflicts are addressed.

**Comment by larainema** [comment]
Hi bufferoverflow, I have tried to merge this pull request but failed as some conflicts, can you update to the latest code and create new pull request?

**Comment by bufferoverflow** [comment]
@larainema any idea about this issue: https://travis-ci.org/fossology/fossology/jobs/50261355

**Comment by bobgob** [comment]
I don’t know but it is a pita for me too.

**Comment by bobgob** [comment]
@bufferoverflow can this be closed without merging?  Haven't these changes been committed already?

**Comment by bufferoverflow** [comment]
I close this PR and provide a new PR as soon as I have some time to do this.

**Pull request closed without merging**
