### PR TITLE
fix(upload): sort upload to reuse select alphabetically

### LINKED ISSUE #710: Upload from file > Reuse: Sort file list alphabetically
In the Upload > From File interface, the user can opt to reuse clearing results from another file. Under point 7, the user can select this file from a list of files displayed in a small window.

Currently, this selection method has has the following problems:
- The file list is not sorted in any recognizable way. I would prefer alphabetical sorting.
- The window is very small, so the user has to scroll a lot.

Ideally, the user would just start typing the file name, and with each character, a list of file starting with the corresponding string would be displayed. But alphabetical sorting would be a start.

### PR DESCRIPTION
**Pull request by max-wittig**
Fixes #710

### CODE REVIEW

**Comment by maximilianhuber** [comment]
same as #767. Maybe move it to a library?

**Comment by max-wittig** [comment]
Moved method to tools.js as requested @maximilianhuber

**Comment by max-wittig** [comment]
Moved method to tools.js as requested @maximilianhuber

**Comment by maximilianhuber** [comment]
merge with #767? This PR does not work without it and is just a single line

**Comment by max-wittig** [comment]
merged with PR #767

**Pull request closed without merging**
