### PR TITLE
Fix regular expression regressions, similar to #879

### PR DESCRIPTION
**Pull request by AMDmi3**
@rlintu please be aware. Related issue: #822

### CODE REVIEW

**Comment by mcjaeger** [comment]
@AMDmi3 I am sorry, apparently merging the PR from rlintu has outdated your branch AMDmi3:regex-fix, would it be OK to rebase this?

**Comment by AMDmi3** [comment]
Sure!

**Comment by mcjaeger** [comment]
@AMDmi3 would you be Ok fixing the conflicts in `src/nomos/agent/STRINGS.in`?

**Comment by AMDmi3** [comment]
Done. Travis failure seem to be unrelated.

**Comment by maxhbr** [comment]
After restarting, all travis tests pass

**Pull request merged**
