### PR TITLE
fix(perm): reading license information and browsing should be allowed with annonymous user

### LINKED ISSUE #996: Anonymous user : "not allowed without login" even when granted to
Hi,
It looks like #994 was not enough to fix some other parts of the UI.

With the following upload config :
screenshot-2018-3-7 edit uploaded file permissions

I got a blank page when trying to click the link with that upload name on the browse page. Ie at URI `/repo/?mod=license&upload=3&folder=1&item=109&show=quick`

And again the same error in logs:

`
[Wed Mar 07 09:37:46.971314 2018] [:error] [pid 196] [client 172.18.0.1:55528] PHP Fatal error:  Uncaught exception 'Exception' with message 'not allowed without login' in /usr/local/share/fossology/lib/php/Plugin/DefaultPlugin.php:323\nStack trace:\n#0 /usr/local/share/fossology/lib/php/Plugin/DefaultPlugin.php(240): Fossology\\Lib\\Plugin\\DefaultPlugin->checkPrerequisites()\n#1 /usr/local/share/fossology/lib/php/Plugin/DefaultPlugin.php(275): Fossology\\Lib\\Plugin\\DefaultPlugin->getResponse()\n#2 /usr/local/share/fossology/www/ui/index.php(62): Fossology\\Lib\\Plugin\\DefaultPlugin->execute()\n#3 {main}\n  thrown in /usr/local/share/fossology/lib/php/Plugin/DefaultPlugin.php on line 323, referer: https://fossology.ow2.org/repo/?mod=browse
`

Overall the same error happens with:
```
/?mod=fileBrowse&upload=3&show=quick&item=109
/?mod=copyright-view&upload=3&show=quick&item=109
```

### PR DESCRIPTION
**Pull request by maxhbr**
closes #996

### CODE REVIEW

**Comment by maxhbr** [comment]
@mhow2, please review this PR

**Comment by maxhbr** [comment]
One could also make the copyright ui visible to not logged in users, but since it also allows editing it would not be a good idea without further work:
```diff
diff --git a/src/copyright/ui/ajax-copyright-hist.php b/src/copyright/ui/ajax-copyright-hist.php
index 86665c4b8..02c1af4e1 100644
--- a/src/copyright/ui/ajax-copyright-hist.php
+++ b/src/copyright/ui/ajax-copyright-hist.php
@@ -46,7 +46,7 @@ class CopyrightHistogramProcessPost extends FO_Plugin
   {                                                                                                                                                                                                                                                           
     $this->Name = "ajax-copyright-hist";                                                                                                                                                                                                                      
     $this->Title = TITLE_copyrightHistogramProcessPost;                                                                                                                                                                                                       
-    $this->DBaccess = PLUGIN_DB_WRITE;                                                                                                                                                                                                                        
+    $this->DBaccess = PLUGIN_DB_READ;                                                                                                                                                                                                                         
     $this->OutputType = 'JSON';                                                                                                                                                                                                                               
     $this->LoginFlag = 0;                                                                                                                                                                                                                                     
     $this->NoMenu = 0;
```

**Comment by mhow2** [comment]
Hi @maxhbr 
Just to make my mind clearer : what are the expected (required) steps to make all the uploads (existing and future) brows-able by the Default User (anonymous) ?

**Comment by mhow2** [comment]
Note: the mod=dashboard is showing a blank page (might be unrelated) and the following errors:

```

fossology-db_1          | 2018-03-19 09:52:30.577 UTC [216] ERROR:  column "procpid" does not exist at character 8
fossology-db_1          | 2018-03-19 09:52:30.577 UTC [216] STATEMENT:  SELECT procpid processid, current_query, query_start, now()-query_start AS elapsed FROM pg_stat_activity WHERE current_query != '<IDLE>' AND datname = 'fossology' ORDER BY procpid
fossology-web_1         | [Mon Mar 19 09:52:30.577652 2018] [:error] [pid 230] [client 172.18.0.1:44406] PHP Warning:  pg_prepare(): Query failed: ERROR:  column &quot;procpid&quot; does not exist\nLINE 1: SELECT procpid processid, current_query, query_start, now()-...\n               ^ in /usr/local/share/fossology/lib/php/Db/Driver/Postgres.php on line 62, referer: http://localhost:8081/repo/?mod=group_manage_users&group=2&gum_pk=2&perm=0
fossology-web_1         | [Mon Mar 19 09:52:30.578104 2018] [:error] [pid 230] [client 172.18.0.1:44406] [2018-03-19 09:52:30] default.CRITICAL: ERROR:  column "procpid" does not exist LINE 1: SELECT procpid processid, current_query, query_start, now()-...                ^ [] [], referer: http://localhost:8081/repo/?mod=group_manage_users&group=2&gum_pk=2&perm=0
fossology-web_1         | [Mon Mar 19 09:52:30.578407 2018] [:error] [pid 230] [client 172.18.0.1:44406] PHP Fatal error:  Uncaught exception 'Fossology\\Lib\\Exception' with message 'error executing: SELECT procpid processid, current_query, query_start, now()-query_start AS elapsed FROM pg_stat_activity WHERE current_query != '<IDLE>' AND datname = 'fossology' ORDER BY procpid -- dashboard::DatabaseQueriesqueryFor_current_query_orderBy_procpid\n\nERROR:  column "procpid" does not exist\nLINE 1: SELECT procpid processid, current_query, query_start, now()-...\n               ^' in /usr/local/share/fossology/lib/php/Db/DbManager.php:141\nStack trace:\n#0 /usr/local/share/fossology/lib/php/Db/ModernDbManager.php(51): Fossology\\Lib\\Db\\DbManager->checkResult(false, 'SELECT procpid ...')\n#1 /usr/local/share/fossology/www/ui/admin-dashboard.php(235): Fossology\\Lib\\Db\\ModernDbManager->prepare('dashboard::Data...', 'SELECT procpid ...')\n#2 /usr/local/share/fossology/www/ui/admin-dashboard.php(374): dashboard->DatabaseQueries()\n#3 /usr/local/share/fossology/lib/php/Plugin/FO_Plugin.php(392): dashboard->Output()\n#4 /usr/local/share/fossology/lib/ph in /usr/local/share/fossology/lib/php/Db/DbManager.php on line 141, referer: http://localhost:8081/repo/?mod=group_manage_users&group=2&gum_pk=2&perm=0

```

**Comment by maxhbr** [comment]
> what are the expected (required) steps to make all the uploads (existing and future) brows-able by the Default User (anonymous) ?

Option 1:
- give anonymous user admin access

Option 2 (better choice):
- give anonymous user read access
- make all uploads readable by every group

**Comment by mhow2** [comment]
Whatever the options I choose, I'm unable to make the Browse link to show up for the anonymous user. I Also set the properties "Public Permission" to "read" from the "Edit Uploaded File Permissions" page with no more success...

**Comment by maxhbr** [comment]
What I have done:
1. give default user read access: 
2. upload as `Make Public`: 
3. browse as logged out user:

**Comment by mhow2** [comment]
Ok I've been able to reproduce your case.
Indeed, it does work from a fresh start, however, if you swap your steps (doing 2) then 1) above), it won't work. Furthermore, even if you upload a second file after this - still with "make public" enabled - browse link won't appear.

In fact, there is no way to make the browse section to appear once you did the steps the other way around...

Can you reproduce and/or is it expected ?

**Comment by mhow2** [comment]
Hi @maxhbr , can you reproduce what I'm saying ?

**Comment by maxhbr** [comment]
Sorry, I was not yet able to find time for that.

**Comment by mcjaeger** [comment]
@maxhbr I am inclined for merging it because it improves the current situation a lot

**Pull request merged**
