### PR TITLE
fix(postgresql): Fixed postgresql version to 9.6 and use a volume for its data.

### LINKED ISSUE #1229: Empty Dashboard site
### Description

Dashboard shows empty page.

#### How to reproduce

1. `git clone https://github.com/fossology/fossology`
2. `cd fossology`
3. `docker-compose up -d`
4. When `docker-compose` finished, visit Fossology and login with `fossy` / `fossy`
5. Visit the Fossology site `/repo/?mod=dashboard`

### Versions

* Last commit id on master: `Version: [3.4.0], Branch: [master], Commit: [#1aed21] 2018/10/18 08:23 UTC built @ 2018/10/22 19:37 UTC`

* Operating System (lsb_release -a):

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic
```

### PR DESCRIPTION
**Pull request by robertvolkmann**
### Changes

There are issues with postgresql versions >= 10.

## How to test

Inspect the logs of `$ docker-compose up` and open the dashboard.

Fixes #1229

### CODE REVIEW

**Comment by ag4ums** [comment]
Hi @robertvolkmann, the issue #1229 has been identified and resolved here PR #1234,
if OK. please close this PR.

**Comment by maxhbr** [comment]
@ag4ums I think both PRs are valid and necessary. This one pins the postgres version and adds a volume for it. #1234 contains a fix to work with postgres 10.

If postgres 10 is tested to work with fossology, one bump the version to 10. Until that we should pin it at a version we know to work.

**Comment by ag4ums** [comment]
@maxhbr thanks for pointing this.

**Comment by mcjaeger** [comment]
looks like pulling works on first sight ...
```
Pulling db (postgres:9.6)...
9.6: Pulling from library/postgres
```

**Pull request merged**
