### PR TITLE
Dev/7809

### PR DESCRIPTION
**Pull request by Dulow187**

### CODE REVIEW

**Comment by bufferoverflow** [comment]
Hi @Dulow187 
please prepare small pull requests read for merge.
this is just a too heavy meal...
cheers
roger

**Comment by steffen-weber** [comment]
@Dulow187: Why do you want to merge into fossology:1.3.1 and not into master?

**Comment by bobgob** [comment]
This pull request  looks like a mistake.  Is that true @Dulow187 ?   Please respond to @bufferoverflow and @steffen-weber above and explain what it is you are trying to do.

**Comment by steffen-weber** [comment]
Since this looks like request by mistake with no response for one month, it will be closed.

**Comment by Dulow187** [comment]
Yeah srry about that  bro i just been  busy over here  thank for the help

**Pull request closed without merging**
