### PR TITLE
fix(reuser): add scancode as dependency if sched

### PR DESCRIPTION
**Pull request by GMishx**
## Description

Add scancode as a dependency to reuser if it is scheduled to create a
correct job queue.

### Changes

Check if scancode agent is scheduled and add it to dependency list.

## How to test

1. Clear an upload with multiple monk bulk jobs.
2. Upload the same package again.
    1. Schedule scancode agent on it.
    2. Schedule the reuser with "Bulk phrases from reused packages" decider option.
3. In the job queue, reuser should not start untill scancode agent finishes.

<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2271"></a>

### CODE REVIEW

**Review by shaheemazmalmmd — APPROVED** [review]
Code looks good. Needs test

**Comment by shaheemazmalmmd** [comment]
Scancode agent is failing on this branch. Please have a look.

```
2022-07-21 12:41:05 scancode [0] :: JOB[206].scancode[75480.localhost]: "/home/fossy/pythondeps/cluecode/copyrights.py:3382: FutureWarning: Possible set difference at position 3" 2022-07-21 12:41:05 scancode [0] :: JOB[206].scancode[75480.localhost]: " 
remove_tags = re.compile(" 2022-07-21 12:41:05 scancode [0] :: JOB[206].scancode[75480.localhost]: "Usage: scancode [OPTIONS]  ..." 2022-07-21 12:41:05 scancode [0] :: JOB[206].scancode[75480.localhost]: "Try the 'scancode --help' option for help on options and arguments." 
2022-07-21 12:41:05 scancode [0] :: JOB[206].scancode[75480.localhost]: "Error: Invalid value for ' ...': Path '-' does not exist." 
2022-07-21 12:41:05 scancode [0] :: JOB[206].scancode[75480.localhost]: "FATAL scancode_wrapper.cc.106: could not execute scancode command: PYTHONPATH='/home/fossy/pythondeps/' SCANCODE_CACHE=/var/local/cache/fossology/scancode /home/fossy/pythondeps/bin/scancode - --custom-output - --custom-template scancode_template.html /srv/fossology/repository/localhost/files/42/e6/e8/42e6e81352fb85e04e38739dacb05a094788483c.3d9060ebc81544e34918df311f9a3fe4.484 --quiet  "
 2022-07-21 12:41:05 scancode [0] :: JOB[206].scancode[75480.localhost]: agent failed with error code 1 2022-07-21 12:41:05 scancode [0] :: JOB[206].scancode[75480.localhost]: agent failed, code: 1

```

**Comment by GMishx** [comment]
> Scancode agent is failing on this branch. Please have a look.

There are no changes done in the scancode agent by this branch. Can you please check if it is failing in the master branch as well?

**Comment by shaheemazmalmmd** [comment]
> > Scancode agent is failing on this branch. Please have a look.
> 
> There are no changes done in the scancode agent by this branch. Can you please check if it is failing in the master branch as well?

@GMishx I have tested master. it is working fine somehow scancode fails here.

**Comment by GMishx** [comment]
Because of the dependency list, scancode was added in the list with empty args by reuser and when actual tried to add, it was prevented.

Updated the code to add args in reuser itself. Please check @shaheemazmalmmd .

**Pull request merged**
