### PR TITLE
feat(fossology): Support for Bionic Beaver

### LINKED ISSUE #1007: Building Fossology 3.2.0 fails on Fedora 27
While building Fossology 3.2.0 on Fedora 27 using the easy-install command, I get compile errors in pkagent.c

The relevant warnings and errors follow. I can upload the entire build output if necessary:

_```
make -s -C pkgagent
make[2]: Entering directory '/home/foss/Source/fossology-3.2.0/src/pkgagent'
writing VERSION file for pkgagent
make[3]: Entering directory '/home/foss/Source/fossology-3.2.0/src/pkgagent/agent'
In file included from pkgagent.h:31:0,
                 from pkgagent.c:31:
/usr/include/rpm/rpmlib.h:20:2: warning: #warning RPM 4.4.x compatibility layer has been removed in RPM >= 4.14 [-Wcpp]
 #warning RPM 4.4.x compatibility layer has been removed in RPM >= 4.14
  ^~~~~~~
pkgagent.c: In function 'ReadHeaderInfo':
pkgagent.c:384:18: warning: implicit declaration of function 'tagName'; did you mean 'ttyname'? [-Wimplicit-function-declaration]
     strcat( fmt, tagName(tag[i]));
                  ^~~~~~~
                  ttyname
pkgagent.c:384:18: warning: passing argument 2 of 'strcat' makes pointer from integer without a cast [-Wint-conversion]
In file included from pkgagent.h:23:0,
                 from pkgagent.c:31:
/usr/include/string.h:129:14: note: expected 'const char * restrict' but argument is of type 'int'
 extern char *strcat (char *__restrict __dest, const char *__restrict __src)
              ^~~~~~
pkgagent.c:387:14: warning: implicit declaration of function 'headerSprintf'; did you mean 'headerWrite'? [-Wimplicit-function-declaration]
     msgstr = headerSprintf(header, fmt, rpmTagTable, rpmHeaderFormats, &errstr);
              ^~~~~~~~~~~~~
              headerWrite
pkgagent.c:387:41: error: 'rpmTagTable' undeclared (first use in this function); did you mean 'rpmTagType'?
     msgstr = headerSprintf(header, fmt, rpmTagTable, rpmHeaderFormats, &errstr);
                                         ^~~~~~~~~~~
                                         rpmTagType
pkgagent.c:387:41: note: each undeclared identifier is reported only once for each function it appears in
pkgagent.c:387:54: error: 'rpmHeaderFormats' undeclared (first use in this function); did you mean 'headerFormat'?
     msgstr = headerSprintf(header, fmt, rpmTagTable, rpmHeaderFormats, &errstr);
                                                      ^~~~~~~~~~~~~~~~
                                                      headerFormat
pkgagent.c:390:16: warning: format '%s' expects argument of type 'char *', but argument 2 has type 'int' [-Wformat=]
       printf("%s:%s\n",tagName(tag[i]),msgstr);
               ~^       ~~~~~~~~~~~~~~~
               %d
make[3]: *** [Makefile:38: pkgagent.o] Error 1
make[3]: Leaving directory '/home/foss/Source/fossology-3.2.0/src/pkgagent/agent'
make[2]: *** [Makefile:30: all] Error 2
make[2]: Leaving directory '/home/foss/Source/fossology-3.2.0/src/pkgagent'
make[1]: *** [Makefile:51: build-pkgagent] Error 2
make[1]: Leaving directory '/home/foss/Source/fossology-3.2.0/src'
make: *** [Makefile:27: build-src] Error 2
```_

### PR DESCRIPTION
**Pull request by GMishx**
## Fixes
1.  Change dependency from heirloom-mailx to heirloom-mailx | s-nail (alias).
1.  Nomos: change sprintf statements to handle longer strings without unexpected results.
1.  Added dependencies for bionic
1.  Change Object class to ObjectType
1.  Added PHP 7.2 tests in Travis as allow failure (can be made necessary)

## Updates
1.  Updated composer dependencies.

## Drop support
**(Already dropped by #1153)**
Dropped support for following distros as they are no longer supported by their producer/developer.

<table>
<thead>
<tr>
<th>Code name</th>
<th>Distro</th>
<th>Version</th>
<th>Link</th>
</tr>
</thead>
<tbody>
<tr>
<td>Lenny</td>
<td>Debian</td>
<td>5</td>
<td><a href="https://wiki.debian.org/DebianLenny" rel="nofollow">https://wiki.debian.org/DebianLenny</a></td>
</tr>
<tr>
<td>Squeeze</td>
<td>Debian</td>
<td>6</td>
<td><a href="https://www.debian.org/releases/squeeze/" rel="nofollow">https://www.debian.org/releases/squeeze/</a></td>
</tr>
<tr>
<td>Hardy</td>
<td>Ubuntu</td>
<td>8.04 </td><td rowspan="9"><a href="https://wiki.ubuntu.com/Releases" rel="nofollow">https://wiki.ubuntu.com/Releases</a></td>
</tr>
<tr>
<td>Lucid</td>
<td>Ubuntu</td>
<td>10.04</td>
</tr>
<tr>
<td>Natty</td>
<td>Ubuntu</td>
<td>11.04</td>
</tr>
<tr>
<td>Oneiric</td>
<td>Ubuntu</td>
<td>11.10</td>
</tr>
<tr>
<td>Precise</td>
<td>Ubuntu</td>
<td>12.04</td>
</tr>
<tr>
<td>Quantal</td>
<td>Ubuntu</td>
<td>12.10</td>
</tr>
<tr>
<td>Raring</td>
<td>Ubuntu</td>
<td>13.04</td>
</tr>
<tr>
<td>Saucy</td>
<td>Ubuntu</td>
<td>13.10</td>
</tr>
<tr>
<td>Yakkety</td>
<td>Ubuntu</td>
<td>16.10</td>
</tr>
<tr>
<td>Isadora</td>
<td>Linux Mint</td>
<td>9</td>
<td><a href="https://blog.linuxmint.com/?p=1403" rel="nofollow">https://blog.linuxmint.com/?p=1403</a></td>
</tr></tbody></table>

Closes #1007

### CODE REVIEW

**Comment by GMishx** [comment]
There is a problem with PHP 7.2 which is the default version of PHP in Ubuntu Bionic.
The [`Object` is a hard reserved keyword](https://secure.php.net/manual/en/migration72.incompatible.php#migration72.incompatible.object-reserved-word) and thus getting the following error:
`PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in /usr/local/share/fossology/lib/php/Util/Object.php on line 5`
Any thoughts on the same?

**Comment by GMishx** [comment]
Changed the class name from `Object` to `ObjectType` to fix the issue. Also need to be updated in the wiki.
https://github.com/fossology/fossology/wiki/PHP-Object-Baseclass (link for the same in Home)

**Comment by GMishx** [comment]
> **NOTE:**
>   The PHP 7.2 test cases are failing on Travis as they require PHPUnit >=7.

To accomplish that, after changing the [PHPUnit version on Travis](https://github.com/fossology/fossology/blob/master/.travis.yml#L62), a call to `composer update` is required. But the Nomos test case is failing on PHPUnit >=6 (it cannot find `agent` table).

**Comment by robertvolkmann** [comment]
Hi @GMishx, I have overlooked your pull request.

Does fossology really need a flag for RPM 4.14? In my understanding pkgagent need only the flag _RPM_4_4. Maybe we should remove all RPM specific flags, because CentOS 5 is EOL and nobody else use RPM in version 4.4.x. I can adjust my pull request to drop RPM 4.4.x.

**Comment by GMishx** [comment]
Thanks @robertvolkmann for the suggestion. And I agree with you. The oldest version of RPM we support should be 4.11. So please go ahead and make the changes in your pull request and I will adjust this PR accordingly.

**Comment by robertvolkmann** [comment]
@GMishx , I have added the changes in my pull request.

**Comment by robertvolkmann** [comment]
Our development dependency does not support PHPUnit 7.

See: https://github.com/mockery/mockery/issues/850

**Pull request merged**
