### PR TITLE
fix(docker): change Dockerfile, docker run command

### PR DESCRIPTION
**Pull request by max-wittig**
remove 'USER fossy' from Dockerfile, /etc/init.d/postgresql cannot be started without being root

### CODE REVIEW

**Comment by maximilianhuber** [comment]
This changes makes the containers run privileged again.

Maybe adding `user: fossy` to the `docker-compose.yml` might be a good replacement to the removed line. (see https://github.com/docker/compose/issues/1532)

**Comment by bufferoverflow** [comment]
I just tested that change and I think we should merge.

**Comment by maximilianhuber** [comment]
Tested for both, singleton- and compose-setup?

**Comment by mcjaeger** [comment]
if review and test is OK, we should merge it, so we have a working docker single container that works for demo purposes when we tag 3.1

**Comment by pguttmann** [comment]
"so we have a working docker single container that works for demo purposes when we tag 3.1" => +1

**Comment by maximilianhuber** [comment]
This PR is related to issue #723

**Comment by maximilianhuber** [comment]
Can you please add the following changes to the file `install/docker-compose.base.yml`:
```diff
diff --git a/install/docker-compose.base.yml b/install/docker-compose.base.yml
index b96e015..f97ebd6 100644
--- a/install/docker-compose.base.yml
+++ b/install/docker-compose.base.yml
@@ -24,3 +24,4 @@ services:
       - FOSSOLOGY_DB_HOST=fossology-db
       - FOSSOLOGY_DB_NAME=fossology
       - FOSSOLOGY_DB_USER=fossy
+    user: fossy
```

I have tested the compose setup with this changes and I would also suggest to merge it.

**Comment by max-wittig** [comment]
updated the changes to `install/docker-compose.base.yml` proposed by @maximilianhuber

**Pull request merged**
