### PR TITLE
contrib(reuse): implement reuse standard 3

### PR DESCRIPTION
**Pull request by GMishx**
## Description

Make FOSSology [reuser standard 3](https://reuse.software/spec/) compliant.

### Changes

Change the copyright and license statements in files.

See following PRs by @rohitpandey49 for changes:
- #2235
- #2238
- #2248
- #2263
- #2264

## How to test

Run [reuse lint](https://git.fsfe.org/reuse/tool)

<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2274"></a>

### CODE REVIEW

**Comment by rohitpandey49** [comment]
Everything is good @GMishx sir.

Screenshot from 2022-07-22 22-31-56

**Comment by GMishx** [comment]
@shaheemazmalmmd , the branch is rebased.

**Comment by shaheemazmalmmd** [comment]
I have tested the branch locally and found that the tool have issues while running.

* Browse

screenShot45

* License Browser

screenShot46

* Copyright information is getting displayed.

screenShot44

**Review by shaheemazmalmmd — APPROVED** [review]
Tested Works as expected.

**Pull request merged**
