### PR TITLE
fix(ci): resolve ninka build dependency

### PR DESCRIPTION
**Pull request by ag4ums**

### CODE REVIEW

**Comment by max-wittig** [comment]
Nice fix, but I also noticed that ninka doesn't work in FOSSology itself, when uploading files, ninka fails to scan. So maybe your fix should be somewhere in the build tools not only in travis.
<pre>2017-04-10 12:43:24 ninka [0] :: JOB[8].ninka[461.localhost]: "Can't locate IO/CaptureOutput.pm in @INC (you may need to install the IO::CaptureOutput module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.20.2 /usr/local/share/perl/5.20.2 /usr/lib/x86_64-linux-gnu/perl5/5.20 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.20 /usr/share/perl/5.20 /usr/local/lib/site_perl .) at /usr/local/share/perl/5.20.2/Ninka/CommentExtractor.pm line 7."
2017-04-10 12:43:24 ninka [0] :: JOB[8].ninka[461.localhost]: "BEGIN failed--compilation aborted at /usr/local/share/perl/5.20.2/Ninka/CommentExtractor.pm line 7."
2017-04-10 12:43:24 ninka [0] :: JOB[8].ninka[461.localhost]: "Compilation failed in require at /usr/local/share/perl/5.20.2/Ninka.pm line 6."
2017-04-10 12:43:24 ninka [0] :: JOB[8].ninka[461.localhost]: "BEGIN failed--compilation aborted at /usr/local/share/perl/5.20.2/Ninka.pm line 6."
2017-04-10 12:43:24 ninka [0] :: JOB[8].ninka[461.localhost]: "Compilation failed in require at /usr/local/bin/ninka line 9."
2017-04-10 12:43:24 ninka [0] :: JOB[8].ninka[461.localhost]: "BEGIN failed--compilation aborted at /usr/local/bin/ninka line 9."
2017-04-10 12:43:24 ninka [0] :: JOB[8].ninka[461.localhost]: "could not execute ninka command: ninka /srv/fossology/repository/localhost/files/c7/25/23/c72523a20fbf241cf69ce95561dd7c46399bb00c.534a3c9393d0ba950d0f4938157ab52b.2437"
2017-04-10 12:43:24 ninka [0] :: JOB[8].ninka[461.localhost]: agent failed with error code 1
2017-04-10 12:43:24 ninka [0] :: JOB[8].ninka[461.localhost]: agent failed, code: 1
</pre>

**Comment by ag4ums** [comment]
@max-wittig, I think we need to install this library IO::CaptureOutput, in the deployment PC also.
Probably need to add this in the fossology-installdeps

**Comment by max-wittig** [comment]
Also why isn't ninka included in the project? Does fossology rely on the ninka github repository to always be working and not introducing breaking changes?

**Comment by mcjaeger** [comment]
Ninka is not included because we do not have someone in the fossology team to maintain it. I have talked to Daniel German about it. The question is not about pulling in Ninka code, but it is the the question who maintain the code in future.

The Ninka wrapper in FOSSology is for users who have installed ninka and then would like to use fossology.

Generally, not having ninka does not break anything, just the package fossology-ninka is not installed and the used should see the ninka selections in the UI.

Maybe we shall pull out ninka from the tests, maybe we could do this in future, I am not sure that this represents an  apparent problem we have currently.

**Comment by max-wittig** [comment]
My change would just use the latest release, instead of using the latest master
https://github.com/dmgerman/ninka/releases

**Comment by mcjaeger** [comment]
again, I am not saying it is bad, it is just not urgent.

**Comment by max-wittig** [comment]
That's true, but then @maximilianhuber needs to remove the ninka script from PR #793

**Comment by maximilianhuber** [comment]
One should also pin the ninka commit

**Comment by max-wittig** [comment]
Did you change your code? You should git clone ninka and checkout 
`81f185261c8863c5b84344ee31192870be939faf` after that. I though it was like that yesterday?

**Comment by maximilianhuber** [comment]
I have created an alternative PR with the above suggested solution at https://github.com/fossology/fossology/pull/799

This also pins the commit.

@max-wittig yes I have edited the comment since it was not correct

**Comment by max-wittig** [comment]
Replaced by PR #799

**Pull request closed without merging**
