### PR TITLE
fix(docker-compose): do not build twice

### PR DESCRIPTION
**Pull request by maxhbr**
This changes the structure of the docker-compose-files. Docker-compose was building the fossology image twice, which is clearly unnecessary.

This also adds a `.dockerignore` file to make the docker images slimmer and to prevent unnecessary rebuilds.

### CODE REVIEW

**Comment by max-wittig** [comment]
Maybe I did something wrong. I ran `docker build -t test .` It did update all the debian dependencies and downloaded ninka, so network connectivity inside the docker container was not the issue.

I got the following error message
<pre>
make -s -C adj2nest
make[2]: Entering directory '/fossology/src/adj2nest'
writing VERSION file for adj2nest
make[3]: Entering directory '/fossology/src/adj2nest/agent'
/usr/bin/ld: ../../../src/lib/c/libfossology.a(libfossscheduler.o): unrecognized relocation (0x2a) in section `.text'
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
Makefile:25: recipe for target 'adj2nest' failed
make[3]: Leaving directory '/fossology/src/adj2nest/agent'
make[3]: *** [adj2nest] Error 1
make[2]: *** [all] Error 2
Makefile:30: recipe for target 'all' failed
make[2]: Leaving directory '/fossology/src/adj2nest'
make[1]: *** [build-adj2nest] Error 2
Makefile:49: recipe for target 'build-adj2nest' failed
make[1]: Leaving directory '/fossology/src'
Makefile:27: recipe for target 'build-src' failed
make: *** [build-src] Error 2
The command '/bin/sh -c make install' returned a non-zero code: 2

</pre>

**Comment by maximilianhuber** [comment]
it works on my local machine and [on travis](https://travis-ci.org/fossology/fossology/jobs/262164619):

**Comment by max-wittig** [comment]
Okay I managed to build the docker container, after recloning fossology. But it seems that the version is not shown. Is that okay? Otherwise everything seems to work
image

**Comment by maximilianhuber** [comment]
The problem is the line https://github.com/fossology/fossology/pull/888/commits/c49d4c056cf0f703517758a07c5dbd4a8c585bc4#diff-f7c5b4068637e2def526f9bbc7200c4eR1, which prevents docker from seeing the `.git` folder. This should reduce the size of the docker images, since the `.git` folder on my system has 292M.

**Comment by maximilianhuber** [comment]
Also I do not want to package the `.git` folder into the container since it might contain confidential or unpublished code.

**Comment by maximilianhuber** [comment]
If one builds the top level Dockerfile one can see the difference
**Old configuration:** `Sending build context to Docker daemon 382.5 MB`
**New configuration:** `Sending build context to Docker daemon 88.96 MB`

**Comment by NesrinCeylan** [comment]
where can I find ninka on WebUI? I start docker-compose in the newes version, but theres no ninka. :/

**Comment by maxhbr** [comment]
Please do not add comments to merged PRs which are not related to the PR. Create an issue instead

**Comment by NesrinCeylan** [comment]
Okay. Sorry, I'll open some issues. Thought it could related and it fits.

>>> Maximilian Huber <notifications@github.com> 22.11.17 15.41 Uhr >>>
Please do not add comments to merged PRs which are not related to the PR. Create an issue instead

**Pull request merged**
