### PR TITLE
feat(spasht): Added Agent Spasht

### PR DESCRIPTION
**Pull request by vivekaindia**
Signed-off-by: vivek kumar <vvksindia@gmail.com>

## Description

Added Agent Spasht With a Basic Configuration UI

## How to test

Run `sudo make install` for the first time.
open an uploaded file.
Check spasht in micro menu options.

### CODE REVIEW

**Comment by vivekaindia** [comment]
@GMishx please restart the job..

**Comment by vivekaindia** [comment]
Thank you @GMishx

**Comment by GMishx** [comment]
@vivekaindia, please rebase with `feat/newagent/spasht` to resolve merge conflicts.

**Comment by vivekaindia** [comment]
Changes were added already in Feat/spasht 1.0

**Pull request closed without merging**
