### PR TITLE
fix(reuser): copy events for reuse

### PR DESCRIPTION
**Pull request by ag4ums**
copying the missing events to be consistent on the license identifier state in the reused package.
Issue :
1. upload a package upload-A, 
2. cleared the component upload-A(with bulk),
3. reuse the component for upload-B.
4. In upload-B file decided with Bulk,(after reuse) 
clicking "submit" on those the file, will change the license identifier state.

### CODE REVIEW

**Comment by mcjaeger** [comment]
there seems to be wrong something with this PR.

Running a simple reuse case (selecting only reuse, not enhanced nor copy bulk scan) yields:

```
2018-04-11 05:58:10 reuser [0] :: JOB[42].reuser[3938.localhost]: "PHP Fatal error:  Class 'Fossology\Reuser\Agent\ClearingEventTypes' not found in /usr/local/share/fossology/reuser/agent/ReuserAgent.php on line 233"
2018-04-11 05:58:10 reuser [0] :: JOB[42].reuser[3938.localhost]: agent failed, code: 255
```

**Comment by mcjaeger** [comment]
adding: same error persists also with clean vagrant based deployment

**Comment by ag4ums** [comment]
need to test & merge this after #978 is closed

**Comment by mcjaeger** [comment]
the error is still there:
```
2018-04-14 21:12:18 reuser [0] :: JOB[22].reuser[27219.localhost]: "PHP Fatal error:  Call to undefined method Fossology\Lib\Data\Clearing\ClearingEvent::getAcknowledgement() in /usr/local/share/fossology/reuser/agent/ReuserAgent.php on line 236"
2018-04-14 21:12:18 reuser [0] :: JOB[22].reuser[27219.localhost]: agent failed, code: 255
```
at `Version: [3.2.0], Branch: [fix/reuser], Commit: [#46ae61] `

**Comment by ag4ums** [comment]
the branch need to rebase with current master.

**Pull request merged**
