### PR TITLE
feat(rest): oidc based authentication

### LINKED ISSUE #515: OAuth2 support
Would be great to have OAuth2 support, this would enable us to
- use standard authentication systems on internal deployments
- use a Mozilla or GitHub account to login on public FOSSology instance

This is related to  #193

### PR DESCRIPTION
**Pull request by GMishx**
## Description

Provide OIDC integration for authentication. Users will be redirected to authentication provider and FOSSology can use the tokens to create a login session.

image

The login integration uses "Authorization Code" flow of OAuth 2.0 and can be configured using "Customize" page, with ability to read .

image

The same OAuth provider can be used for REST API authentication as well with "Client Credentials" flow.

image

The existing token mechanism will still exist and can be configured from `fossology.conf`. A new section `AUTHENTICATION` is added with 2 parameters `provider` and `resttoken`.
Setting `provider` to `external` will prevent logins with username & password. The mechanism for REST authentication can be set by editing `resttoken`.

image

## How to test

1. Setup OIDC authentication with FOSSology and check if it works.
2. Check if logout mechanism works.
3. Test the REST authentication with old tokens and OIDC.
4. Test if changing `resttoken` in `fossology.conf` effects the token authentication in REST API.
5. Check if changing `provider` in `fossology.conf` to `external` prevents login with username and password.

Closes #515

<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2123"></a>

### CODE REVIEW

**Review by ag4ums — APPROVED** [review]
code looks good working as expected.

**Comment by kannan1997** [comment]
Hi @GMishx, 

We are trying to implement the OIDC feature for our fossology server, however, we are facing issues while configuring. 
Can you please provide us documentation for configuring, this will be really helpful. 

Error log from UI:  Invalid issuer of token.
No error logs from the backend.

**Comment by GMishx** [comment]
Hello @kannan1997, you can find the documentation here https://github.com/fossology/fossology/wiki/OpenID-Connect-authentication-configuration

Do let us know if it needs any modifications.

**Comment by hoangnt2** [comment]
@GMishx, As I understand, if I want to use OIDC authentication in fossology, I need to have an existing user in fossology with the same email as the user in OIDC provider. Is this correct?

**Comment by GMishx** [comment]
Yes @hoangnt2 , that is correct, the user must exist beforehand in FOSSology.
Either the username or the email field for the user should match the value provided by OIDC provider.
You can customize the field with userid provided by OIDC provider with "Resource owner id field" field in FOSSology's customize page.

**Comment by hoangnt2** [comment]
@GMishx, thanks for your information

**Pull request merged**
