### PR TITLE
feat(CI): Migrate API docs generation and deployment to GitHub Actions

### PR DESCRIPTION
**Pull request by avinal**
## Description

Migrate API docs generation and deployment to GitHub Actions from Travis CI.

### Changes

List the changes done to fix a bug or introducing a new feature.
- Added new workflow script for GitHub Actions: pages-deploy.yml
- Removed pages deployment from Travis CI: .travis.yml
- Modified pages-deployment script for GHA: pages-deploy.sh

## How to test

Describe the steps required to test the changes proposed in the pull request.
Check the current deployment at http://avinal.space/checkdeployment/

Please consider using the closing keyword if the pull request is proposed to
fix an issue already created in the repository
(https://help.github.com/articles/closing-issues-using-keywords/)
Fixes part of #1913

### CODE REVIEW

**Comment by avinal** [comment]
I am a bit confused about if this should run on each `push` or `release`. The release is a better choice. Please let me know I will change it then.

**Comment by GMishx** [comment]
How about using https://github.com/marketplace/actions/github-pages-action to handle the commit pushes? It keeps the code clean.
It also allows to use the default `GITHUB_TOKEN` with `github_token` option.

It also allows to set `external_repository`, `force_orphan`, `commit_message`, `user_name` and `user_email`.

> I am a bit confused about if this should run on each `push` or `release`.

It should be done whenever there is a merge (`push`) to master not on releases as the documents get updated with the code.

**Comment by avinal** [comment]
Yeah, I considered using this (https://github.com/marketplace/actions/github-pages-action) initially, but I thought maybe this project needs some customizations and fewer dependencies, so I created a custom one. (I should have asked) No Worries. I will refactor the workflow to use it. 

But still, I don't think you can use `GITHUB_TOKEN` to deploy to another repo. It is only repo scoped. You can see it that action's readme too: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-deploy-to-external-repository-external_repository
Official Doc: https://docs.github.com/en/actions/reference/authentication-in-a-workflow

`push` is already the default option :)

**Comment by GMishx** [comment]
It is okay to use dependencies as long as they are compatible with GPL-2.0 license. It takes some load off from maintaining the code.

And for `GITHUB_TOKEN`, I missed that point. Thanks for pointing it. Please change it to `personal_token` and will setup one in the secrets.

**Comment by avinal** [comment]
New Changes:
- Page deployment is being handled by [peaceiris/github-pages-action](https://github.com/peaceiris/actions-gh-pages)
- `external_repository: ${{ secrets.GH_REPO_REF }}` - assuming `GH_REPO_REF` is set to **fossology/fossology.github.io** 
- Authentication set to `personal_token` - Please add a secret named `GH_TOKEN`

I think it is all complete now 👍

**Review by GMishx — APPROVED** [review]
Changes looks good.

**Comment by GMishx** [comment]
Just saw your deployment and found the version number missing:
image

It is fetched from git and requires the history to find the first tag. Maybe the checkout depth needs to be increased?
https://github.com/fossology/fossology/blob/eb0319dced8f0b4dd4fd7e5db5d654e0cd64bd4e/utils/deploy-pages.sh#L31-L33

**Comment by avinal** [comment]
I think it will work here because my deployment is based on my fork only and it has no tags, so it can't get any. For a test, we can do one thing add an `echo $CURR_TAG` after line 33 and see the logs it detects or not. If yes then we are good to go.

**Comment by GMishx** [comment]
> I think it will work here because my deployment is based on my fork only and it has no tags, so it can't get any.

Can you please try to create some tags on your fork? As per the current state (https://github.com/fossology/fossology/releases/tag/3.10.0-rc1), there are at least 66 commits since last tag. So a tag 70 commits back from your test commit should be fine.

> For a test, we can do one thing add an `echo $CURR_TAG` after line 33 and see the logs it detects or not. If yes then we are good to go.

What you suggest is to remove the **"Run on master"** condition and print `CURR_TAG` for this PR?

**Comment by avinal** [comment]
I saw some solutions on StackOverflow, one of the solutions is definitely increasing the fetch depth, so I will hardcode it for a test and see if it works. 

> What you suggest is to remove the **"Run on master"** condition and print `CURR_TAG` for this PR?

Kinda yes, because in my test run this is the error `fatal: No tags can describe '3e89fc845add6a7970c9aa2296fab163a7eb84e2'` I will get back after the test shortly.

**Comment by avinal** [comment]
image
Increasing fetch-depth worked, adding that in a moment.

**Review by GMishx — APPROVED** [review]
Tested at https://avinal.space/checkdeployment/

**Comment by GMishx** [comment]
Yay! Deployment successful: https://github.com/fossology/fossology/actions/runs/679189817
https://fossology.github.io/

**Pull request merged**
