### PR TITLE
feat(ununpack): Creating logs if an unpack attempt fails

### PR DESCRIPTION
**Pull request by GMishx**
## Enhancements
1.  Preserve the unpack tool output for log purpose.
1.  Use popen() instead of system() to capture program output.
1.  Print the output to log if tool's return code is `NOT OK` or if verbose mode is on.

## Changes
*  **Departition:** Put few messages in verbose only preventing unwanted output.
*  **ununpack.c**: Change the alignments.

## How to test
1.  Upload a normal file with verbose off.
    -  No log should be generated.
1.  Upload a normal file with verbose on.
    -  Log should contain information form tool.
1.  Upload a dirty package with verbose off.
    -  Log should contain the failure message along with return code.
1.  Upload a dirty package with verbose on.
    -  Log should contain the failure message along with return code.

>  P.S. Log mentioned is the one which comes in **Geeky Scan Details**.

### CODE REVIEW

**Comment by mcjaeger** [comment]
asking please for a test file ("dirty package")? because if I upload `src/ununpack/agent_tests/testdata/testdata.tar.bz2`then the log shows:

```
2018-07-10 08:48:07 ununpack [0] :: JOB[22].ununpack[3031.localhost]: "ERROR traverse.c.216: pfile 1113 Command unrar failed on: /srv/fossology/repository/vagrant-ubuntu-trusty-64/ununpack/432519l/a8cd486cd62a561ed88f4fe9e32210d015f41c46.b556142be0bfabaf4daaf1f356eac5e7.619795.dir/testdata.tar.dir/Test-0001.rar"
2018-07-10 08:48:08 ununpack [0] :: JOB[22].ununpack[3031.localhost]: "ERROR traverse.c.216: pfile 1113 Command unrar failed on: /srv/fossology/repository/vagrant-ubuntu-trusty-64/ununpack/432519l/a8cd486cd62a561ed88f4fe9e32210d015f41c46.b556142be0bfabaf4daaf1f356eac5e7.619795.dir/testdata.tar.dir/test.rar"
2018-07-10 08:48:09 ununpack [0] :: JOB[22].ununpack[3031.localhost]: "ERROR traverse.c.337: pfile 1113 "/srv/fossology/repository/vagrant-ubuntu-trusty-64/ununpack/432519l/a8cd486cd62a561ed88f4fe9e32210d015f41c46.b556142be0bfabaf4daaf1f356eac5e7.619795.dir/testdata.tar.dir/test.iso.dir/test1.zip.tar.dir/test1.zip.dir/test.dir/test.jar.dir" DOES NOT EXIST!!!"
2018-07-10 08:48:09 ununpack [0] :: JOB[22].ununpack[3031.localhost]: "ERROR traverse.c.337: pfile 1113 "/srv/fossology/repository/vagrant-ubuntu-trusty-64/ununpack/432519l/a8cd486cd62a561ed88f4fe9e32210d015f41c46.b556142be0bfabaf4daaf1f356eac5e7.619795.dir/testdata.tar.dir/test.iso.dir/test1.zip.tar.dir/test1.zip.dir/test.dir/test.dir2/test.jar.dir" DOES NOT EXIST!!!"
```

-> output is already there.

**Comment by GMishx** [comment]
I will try to collect some more test files and will provide you.
But for the same package, if you compare the outputs of `master` and `GMishx:feat/ununpackerrorlog`

#### master
```
2018-07-11 13:20:35 ununpack [0] :: JOB[51].ununpack[26685.localhost]: "ERROR traverse.c.337: pfile 165844 "/srv/fossology/repository/gaurav-VirtualBox/ununpack/623787l/a8cd486cd62a561ed88f4fe9e32210d015f41c46.b556142be0bfabaf4daaf1f356eac5e7.619795.dir/testdata.tar.dir/test.iso.dir/test1.zip.tar.dir/test1.zip.dir/test.dir/test.zip.dir" DOES NOT EXIST!!!"
2018-07-11 13:20:35 ununpack [0] :: JOB[51].ununpack[26685.localhost]: "ERROR traverse.c.337: pfile 165844 "/srv/fossology/repository/gaurav-VirtualBox/ununpack/623787l/a8cd486cd62a561ed88f4fe9e32210d015f41c46.b556142be0bfabaf4daaf1f356eac5e7.619795.dir/testdata.tar.dir/test.iso.dir/test1.zip.tar.dir/test1.zip.dir/test.dir/test.jar.dir" DOES NOT EXIST!!!"
2018-07-11 13:20:35 ununpack [0] :: JOB[51].ununpack[26685.localhost]: "ERROR traverse.c.337: pfile 165844 "/srv/fossology/repository/gaurav-VirtualBox/ununpack/623787l/a8cd486cd62a561ed88f4fe9e32210d015f41c46.b556142be0bfabaf4daaf1f356eac5e7.619795.dir/testdata.tar.dir/test.iso.dir/test1.zip.tar.dir/test1.zip.dir/test.dir/test.dir2/test.zip.dir" DOES NOT EXIST!!!"
2018-07-11 13:20:35 ununpack [0] :: JOB[51].ununpack[26685.localhost]: "ERROR traverse.c.337: pfile 165844 "/srv/fossology/repository/gaurav-VirtualBox/ununpack/623787l/a8cd486cd62a561ed88f4fe9e32210d015f41c46.b556142be0bfabaf4daaf1f356eac5e7.619795.dir/testdata.tar.dir/test.iso.dir/test1.zip.tar.dir/test1.zip.dir/test.dir/test.dir2/test.jar.dir" DOES NOT EXIST!!!"
```

#### GMishx:feat/ununpackerrorlog
```
2018-07-11 13:22:59 ununpack [0] :: JOB[59].ununpack[7187.localhost]: "ERROR traverse.c.337: pfile 165844 "/srv/fossology/repository/gaurav-VirtualBox/ununpack/180938l/a8cd486cd62a561ed88f4fe9e32210d015f41c46.b556142be0bfabaf4daaf1f356eac5e7.619795.dir/testdata.tar.dir/test.iso.dir/test1.zip.tar.dir/test1.zip.dir/test.dir/test.zip.dir" DOES NOT EXIST!!!"
2018-07-11 13:22:59 ununpack [0] :: JOB[59].ununpack[7187.localhost]: "ERROR traverse.c.337: pfile 165844 "/srv/fossology/repository/gaurav-VirtualBox/ununpack/180938l/a8cd486cd62a561ed88f4fe9e32210d015f41c46.b556142be0bfabaf4daaf1f356eac5e7.619795.dir/testdata.tar.dir/test.iso.dir/test1.zip.tar.dir/test1.zip.dir/test.dir/test.jar.dir" DOES NOT EXIST!!!"
2018-07-11 13:22:59 ununpack [0] :: JOB[59].ununpack[7187.localhost]: "ERROR traverse.c.337: pfile 165844 "/srv/fossology/repository/gaurav-VirtualBox/ununpack/180938l/a8cd486cd62a561ed88f4fe9e32210d015f41c46.b556142be0bfabaf4daaf1f356eac5e7.619795.dir/testdata.tar.dir/test.iso.dir/test1.zip.tar.dir/test1.zip.dir/test.dir/test.dir2/test.zip.dir" DOES NOT EXIST!!!"
2018-07-11 13:22:59 ununpack [0] :: JOB[59].ununpack[7187.localhost]: "ERROR traverse.c.337: pfile 165844 "/srv/fossology/repository/gaurav-VirtualBox/ununpack/180938l/a8cd486cd62a561ed88f4fe9e32210d015f41c46.b556142be0bfabaf4daaf1f356eac5e7.619795.dir/testdata.tar.dir/test.iso.dir/test1.zip.tar.dir/test1.zip.dir/test.dir/test.dir2/test.jar.dir" DOES NOT EXIST!!!"
2018-07-11 13:23:00 ununpack [0] :: JOB[59].ununpack[7187.localhost]: "sh: 1: Syntax error: redirection unexpected"
2018-07-11 13:23:00 ununpack [0] :: JOB[59].ununpack[7187.localhost]: "ERROR traverse.c.216: pfile 165844 Command 7z failed on: /srv/fossology/repository/gaurav-VirtualBox/ununpack/180938l/a8cd486cd62a561ed88f4fe9e32210d015f41c46.b556142be0bfabaf4daaf1f356eac5e7.619795.dir/testdata.tar.dir/test.exe"
2018-07-11 13:23:01 ununpack [0] :: JOB[59].ununpack[7187.localhost]: "ERROR utils.c.598: RC: 2, error: 7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18"
2018-07-11 13:23:01 ununpack [0] :: JOB[59].ununpack[7187.localhost]: "ERROR utils.c.598: RC: 2, error: p7zip Version 9.20 (locale=en_IN,Utf16=on,HugeFiles=on,4 CPUs)"
2018-07-11 13:23:01 ununpack [0] :: JOB[59].ununpack[7187.localhost]: "ERROR utils.c.598: RC: 2, error: Error: /srv/fossology/repository/gaurav-VirtualBox/ununpack/180938l/a8cd486cd62a561ed88f4fe9e32210d015f41c46.b556142be0bfabaf4daaf1f356eac5e7.619795.dir/testdata.tar.dir/Test-0001.rar.dir/Test/Map0001.lmu: Can not open file as archive"
2018-07-11 13:23:01 ununpack [0] :: JOB[59].ununpack[7187.localhost]: "ERROR utils.c.598: RC: 2, error: Errors: 1"
2018-07-11 13:23:01 ununpack [0] :: JOB[59].ununpack[7187.localhost]: "ERROR utils.c.598: RC: 2, error: 7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18"
2018-07-11 13:23:01 ununpack [0] :: JOB[59].ununpack[7187.localhost]: "ERROR utils.c.598: RC: 2, error: p7zip Version 9.20 (locale=en_IN,Utf16=on,HugeFiles=on,4 CPUs)"
2018-07-11 13:23:01 ununpack [0] :: JOB[59].ununpack[7187.localhost]: "ERROR utils.c.598: RC: 2, error: Processing archive: /srv/fossology/repository/gaurav-VirtualBox/ununpack/180938l/a8cd486cd62a561ed88f4fe9e32210d015f41c46.b556142be0bfabaf4daaf1f356eac5e7.619795.dir/testdata.tar.dir/Test-0001.rar.dir/Test/Map0001.lmu"
2018-07-11 13:23:01 ununpack [0] :: JOB[59].ununpack[7187.localhost]: "ERROR utils.c.598: RC: 2, error: Error: Can not open file as archive"
2018-07-11 13:23:01 ununpack [0] :: JOB[59].ununpack[7187.localhost]: "ERROR utils.c.598: RC: 2, error: "
```

The logs in master miss the unpack failure of **testdata.tar.dir/test.exe** and **testdata.tar.dir/Test-0001.rar.dir/Test/Map0001.lmu**.

**Comment by mcjaeger** [comment]
@GMishx please consider updating at some point.

**Comment by GMishx** [comment]
Unable to find a case where these changes will be helpful. Closing this PR now but keeping the branch open in case someone finds something and wants to continue.

**Pull request closed without merging**
