### PR TITLE
docs(SCANOSS): updated documentation for the SCANOSS agent

### PR DESCRIPTION
**Pull request by ortizjeronimo**
## Description

This pull request updates the documentation for the SCANOSS agent, including:

- Configuration
- Usage
- Screenshots

Updated the [README.MD file](https://github.com/fossology/fossology/blob/master/src/scanoss/README.MD) for the SCANOSS Agent, and added pictures to src/scanoss/pics.

### Changes

Added more information and screenshots.

### CODE REVIEW

**Comment by EttingerK** [comment]
Thank you all for updating the Readme. We are wondering how to do the configuration of SCANOSS in FOSSology: 
Admin - Customize - SCANOSS config (please look at the picture)
image

**Comment by scanossjeronimo** [comment]
Hello @EttingerK 

Sure, let me do another commit including how to configure SCANOSS in FOSSology.

**Comment by shaheemazmalmmd** [comment]
@scanossjeronimo :  Thank you for your contribution. can you please squash your commits to one ?? and also add the commit message according to our [contributing](https://github.com/fossology/fossology/blob/master/CONTRIBUTING.md) guidelines?

**Comment by scanossjeronimo** [comment]
Hello Shaheem,

I updated the PR, please contact me in case of further modification.

Regards,
Jeronimo.
________________________________

**Comment by scanossjeronimo** [comment]
Hello @shaheemazmalmmd 

Double checking with you, if the PR is okay for merging.

**Comment by shaheemazmalmmd** [comment]
> Hello @shaheemazmalmmd
> 
> Double checking with you, if the PR is okay for merging.

Hello @scanossjeronimo ,

I have observed that the commits are not yet squashed see (https://www.freecodecamp.org/news/git-squash-commits/) and also change commit message according to our [contributing](https://github.com/fossology/fossology/blob/master/CONTRIBUTING.md) guidelines.

**Comment by scanossjeronimo** [comment]
@shaheemazmalmmd Can you please provide how the message would look like I think the commit title is good as it is

**Comment by scanossjeronimo** [comment]
@shaheemazmalmmd I think PR is now ready!

**Comment by shaheemazmalmmd** [comment]
> @shaheemazmalmmd I think PR is now ready!



> @shaheemazmalmmd I think PR is now ready!

@ortizjeronimo : There are still 7 commits in this PR can you squash them to 1 ?

**Comment by ortizjeronimo** [comment]
@shaheemazmalmmd I just squashed the commits into 1

**Review by shaheemazmalmmd — APPROVED** [review]
DOC looks Good.

**Pull request merged**
