### PR TITLE
fix(docker): revert docker and docker-compose to older, working state

### PR DESCRIPTION
**Pull request by max-wittig**
As coordinated with @bufferoverflow and @mcjaeger 
This also enables the use of E2E selenium tests with Travis CI later on...

### CODE REVIEW

**Comment by mcjaeger** [comment]
let's keep ninka testing otherwise we need to remove the ninca wrapper code from the repo as well.
@ag4ums has developed a fix for that
 
>   # TO resolve ninka build dependency
>   - git clone --branch release-1.1104 https://github.com/dagolden/IO-CaptureOutput.git
>   - cd IO-CaptureOutput && perl Makefile.PL && make && make test && make install && cd ..
>   - rm -rf IO-CaptureOutput

let's use this.

**Comment by mcjaeger** [comment]
@maximilianhuber  please let us know in case you would like to have some time review or work on this.

**Comment by maximilianhuber** [comment]
@mcjaeger yes, that would be great. I will try to fix the bug this weekend to prevent the rollback of the docker setup.

**Comment by bufferoverflow** [comment]
The big question here is , when shall the release happen. @max-wittig has some time to make this ready today and add the ninka fix, mission complete.

We can always add the other stuff again if @maximilianhuber is successful at the weekend.

**Comment by bufferoverflow** [comment]
Have this ready and integrate #787 is much more important from my perspective.

**Comment by mcjaeger** [comment]
integrate #787 into docker and travis-ci? or only travis-ci?

if maximilian asks for few days it is just fair to wait.

**Comment by maximilianhuber** [comment]
Please have a look at the PR https://github.com/fossology/fossology/pull/793 which fixes the problem by reverting the root Dockerfile (the same way as this PR does). But I do not revert the compose setup, instead I move the complex Dockerfile to `install/docker-compose.Dockerfile`. Thus we still have a setup which runs as non privileged user.

**Comment by maximilianhuber** [comment]
The commit 2d8474c is not related to docker. Please move it to its own PR.

**Comment by maximilianhuber** [comment]
This breaks the tests. Please fix the following
```
RROR: Can't create '/usr/local/man/man3'
Do not have write permissions on '/usr/local/man/man3'
```
(after moving it to its own PR)

**Comment by max-wittig** [comment]
How to fix that?

**Comment by maximilianhuber** [comment]
you might need to add `sudo` to be able to do the `make install`

**Comment by max-wittig** [comment]
replaced by PR #793

**Pull request closed without merging**
