### PR TITLE
feat(license): use spdx identifiers for reporting licenses

### LINKED ISSUE #748: Regression: GPL-2.1[sic] license generates invalid SPDX file
This was previously reported in #643 and fixed in PR #633, but appears to be broken again. The steps to reproduce are the same:

Steps to reproduce:
1. Upload from URL https://gist.githubusercontent.com/timurphy/56eb73da5992bf4423af/raw/6273b0b41d25f741a53b2bff52626b1d4f56a698/lgpl_sic.txt with Nomos scan enabled
2. Generate SPDX:RDF file
3. Using the [spdx tools](https://github.com/spdx/tools) project, run the Verify command, which will print this error:

```
This SPDX Document is not valid due to:
	Invalid license id 'LicenseRef-GPL-2.1[sic]'.  Must start with 'LicenseRef-' and made up of the characters from the set 'a'-'z', 'A'-'Z', '0'-'9', '+', '_', '.', and '-'.
```

Tested on Version: [3.1.0rc2], Branch: [master], Commit: [#3b080b]

### LINKED ISSUE #1061: GPL / LGPL short-identifier  name change, proposal for 3.4.0
Short license identifiers have been changed in SPDX-3.0 from GPL-2.0 style to GPL-2.0-only and LGPL-2.0+ style to LGP-2.0-or-later.
My proposal is that this change is not done for 3.3.0 but for 3.4.0.

### LINKED ISSUE #1365: SPDX2 tag:value uses a deprecated LGPL (and therefore is not SPDX valid)
### Description

The tag-value version of SPDX report generated is not valid SPDX. The culprit seems to be “LGPL-2.1”, so I suspect it has to do with the renaming of the *GPL family of licenses and the change from “+” to “-or-later”/“-only”.

Oddly enough, the RDF version of the same scan passes as valid SPDX though.

#### How to reproduce

1. upload something with LGPL in it (probably works with GPL and AGPL as well)
2. do your normal audit (probably optional step)
3. generate SPDX tag-value report
4. check with SPDX Tools for validity of the file

#### Screenshots

```
java -jar /home/hook/SPDX/tools/target/spdx-tools-2.1.12-jar-with-dependencies.jar  Verify SPDX2TV_<…>.spdx
```
produces the following error:

```
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console. Set system property 'log4j2.debug' to show Log4j2 internal initialization logging.
This SPDX Document is not valid due to:
        Relationship at line 44 invalid: LGPL-2.1 is deprecated. in <…>.zip
        Package at line 29 invalid: LGPL-2.1 is deprecated. in <…>.zip
```
### Versions

* Last commit id on master: [3.5.0], Branch: [HEAD], Commit: [#171d4d] 2019/04/12 08:47 UTC built @ 2019/04/12 09:09 UTC

### PR DESCRIPTION
**Pull request by GMishx**
## Description
Add new field called as "SPDX ID" to all licenses allowing users/admins to add valid SPDX License Identifier to all licenses. This new ID will be used in all reports generated by FOSSology to get the license name.

In case, the field is empty, it will fallback to license's shortname, the current behavior.

image

At the same time, update nomos to spit out new SPDX identifiers for licenses like `GPL-2.0` to `GPL-2.0-only`.

### Changes

1. Rename field `rf_spdx_compatible` to `rf_spdx_id` in `license_ref` table.
2. Use the new field for license name in reports dao.
3. New function `getProjectedSpdxId()` to `LicenseMap`, used to get license name in reports.
4. Fix CLIXML report.
5. Update license names in nomos to use new SPDX naming standards.

## How to test

1. Install FOSSology and scan some package.
2. Make sure FOSSology display's new SPDX names for licenses.
3. Update SPDX ID for some identified licenses and generate reports.
4. Check if the report contains updated SPDX ID for license name.
5. For licenses missing SPDX ID, the report should contain license's shortname.

<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2363"></a>

Closes #748
Closes #1061
Closes #1365

### CODE REVIEW

**Comment by GMishx** [comment]
@ag4ums @shaheemazmalmmd @NicolasToussaint , a suggestion to make this PR more effective.

Can we use the license identifier as `LicenseRef-fossology-<shortname>` in case the user has not filled in the new "SPDX ID" field for the license? Currently, if the filed is empty, FOSSology fallback to shortname.

In my opinion, doing so, we can enforce users to fill "SPDX ID" field with appropriate name and at the same time, be SPDX compliant. WDYT?

**Comment by shaheemazmalmmd** [comment]
> @ag4ums @shaheemazmalmmd @NicolasToussaint , a suggestion to make this PR more effective.
> 
> Can we use the license identifier as `LicenseRef-fossology-<shortname>` in case the user has not filled in the new "SPDX ID" field for the license? Currently, if the filed is empty, FOSSology fallback to shortname.
> 
> In my opinion, doing so, we can enforce users to fill "SPDX ID" field with appropriate name and at the same time, be SPDX compliant. WDYT?

@GMishx I agree with your proposal. if the user doesn't provide proper SPDX identifier then fossology should report the license as `LicenseRef-fossology-<shortname>`. so that the tool shall be SPDX compliant.

**Comment by shaheemazmalmmd** [comment]
Post-install scripts are producing warnings please check

```
PHP Warning:  pg_execute(): Query failed: ERROR:  duplicate key value violates unique constraint "rf_md5unique"

DETAIL:  Key (rf_md5)=(1071684ac211f5e00f2e891ad2315c80) already exists. in /usr/local/share/fossology/lib/php/Db/Driver/Postgres.php on line 59

PHP Stack trace:

PHP   1. {main}() /usr/local/lib/fossology/fossinit.php:0

PHP   2. initLicenseRefTable($Verbose = FALSE) /usr/local/lib/fossology/fossinit.php:231

PHP   3. insertNewLicense($dbManager = class Fossology\Lib\Db\ModernDbManager { protected $dbDriver = class Fossology\Lib\Db\Driver\Postgres { private $dbConnection = class PgSql\Connection { ... } }; protected $preparedStatements = ['fo_libschema::addInheritedRelations' => 'SELECT class.relname AS "table", daddy.relname AS inherits_from\n      FROM pg_class AS class\n      INNER JOIN pg_catalog.pg_inherits ON pg_inherits.inhrelid = class.oid\n      INNER JOIN pg_class daddy ON pg_inherits.inhparent = daddy.oid', 'fo_libschema::addTables' => 'SELECT\n    table_name AS "table", ordinal_position AS ordinal, column_name,\n    udt_name AS type, character_maximum_length AS modifier,\n    CASE is_nullable WHEN \'YES\' THEN false WHEN \'NO\' THEN true END AS "notnull",\n    column_default AS "default",\n    col_description(table_name::regclass, ordinal_position) AS description\n  FROM information_schema.columns\n  WHERE table_schema = \'public\'\n  ORDER BY table_name, ordinal_position;', 'fo_libschema::addViews' => 'SELECT viewname,definition FROM pg_views WHERE viewowner = $1', 'fo_libschema::addSequences' => 'SELECT relname\n      FROM pg_class\n      WHERE relkind = \'S\'\n        AND relnamespace IN (\n             SELECT oid FROM pg_namespace WHERE nspname NOT LIKE \'pg_%\' AND nspname != \'information_schema\'\n            )', 'fo_libschema::addConstraints' => 'SELECT c.conname AS constraint_name,\n        CASE c.contype\n          WHEN \'c\' THEN \'CHECK\'\n          WHEN \'f\' THEN \'FOREIGN KEY\'\n          WHEN \'p\' THEN \'PRIMARY KEY\'\n          WHEN \'u\' THEN \'UNIQUE\'\n        END AS type,\n        CASE WHEN c.condeferrable = \'f\' THEN 0 ELSE 1 END AS is_deferrable,\n        CASE WHEN c.condeferred = \'f\' THEN 0 ELSE 1 END AS is_deferred,\n        t.relname AS table_name, array_to_string(c.conkey, \' \') AS constraint_key,\n        CASE confupdtype\n          WHEN \'a\' THEN \'NO ACTION'..., 'fo_libschema::addIndexes' => 'SELECT tablename AS "table", indexname AS index, indexdef AS define\n      FROM pg_indexes\n      INNER JOIN information_schema.tables ON table_name = tablename\n        AND table_type = \'BASE TABLE\'\n        AND table_schema = \'public\'\n        AND schemaname = \'public\'\n      ORDER BY tablename,indexname;\n    ', 'Fossology\Lib\Db\DbManager::createMap.sysconfig.variablename,conf_value' => 'select variablename,conf_value from sysconfig', 'checkAuthorCtPkSequence' => 'SELECT count(*) FROM pg_class WHERE relname = \'author_pk_seq\';', 'fo_libschema::applySchema.getTimeout' => 'show statement_timeout', 'fo_libschema::dropViews' => 'SELECT view_name,table_name,column_name\n        FROM information_schema.view_column_usage\n        WHERE table_catalog=\'fossology\'\n        ORDER BY view_name,table_name,column_name', 'fo_libschema::applySchema.resetTimeout' => 'SET statement_timeout = 0', 'license_ref.count' => 'SELECT count(*) FROM license_ref', 'insertInToLicenseRefTableUsingJson.insertInTolicense_ref_2' => 'INSERT INTO license_ref_2 ( marydone,"rf_FSFfree","rf_Fedora","rf_GPLv2compatible","rf_GPLv3compatible","rf_OSIapproved",rf_active,rf_add_date,rf_copyleft,rf_detector_type,rf_flag,rf_fullname,rf_notes,rf_risk,rf_shortname,rf_source,rf_spdx_id,rf_text,rf_text_updatable,rf_url,rf_md5 ) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,md5($21));', 'initLicenseRefTable.newLic' => 'SELECT * FROM license_ref_2', 'initLicenseRefTable.licenseRefByShortname' => 'SELECT *,md5(rf_text) AS hash FROM license_ref WHERE rf_shortname=$1', 'isLicenseExists.license_candidate' => 'SELECT * FROM ONLY license_candidate WHERE rf_shortname = $1;', 'initLicenseRefTable.updateLicenseRef.spdxId' => 'UPDATE license_ref SET rf_spdx_id=$1 WHERE rf_shortname=$2;', 'insertNewLicense.insertNewLicense.returning:rf_pk' => 'INSERT INTO license_ref (rf_shortname, rf_text, rf_url, rf_fullname, rf_notes, rf_active, rf_text_updatable, rf_detector_type, marydone, rf_spdx_id, rf_md5, rf_add_date) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,md5($11),now()) RETURNING rf_pk']; protected $logger = class Monolog\Logger { protected $name = '/usr/local/share/fossology/lib/php/libschema.php'; protected $handlers = [...]; protected $processors = [...]; protected $microsecondTimestamps = TRUE; protected $timezone = class DateTimeZone { ... }; protected $exceptionHandler = NULL; private $logDepth = 0; private $detectCycles = TRUE }; protected $cumulatedTime = ['fo_libschema::addInheritedRelations' => 0.0034422874450684, 'fo_libschema::addTables' => 0.20629072189331, 'fo_libschema::addViews' => 0.014699697494507, 'fo_libschema::addSequences' => 0.002601146697998, 'fo_libschema::addConstraints' => 0.015281915664673, 'fo_libschema::addIndexes' => 0.3996798992157, 'Fossology\Lib\Db\DbManager::createMap.sysconfig.variablename,conf_value' => 0.00050091743469238, 'checkAuthorCtPkSequence' => 0.00096797943115234, 'fo_libschema::applySchema.getTimeout' => 0.00045990943908691, 'fo_libschema::dropViews' => 0.016739130020142, 'fo_libschema::applySchema.resetTimeout' => 0.00034594535827637, 'license_ref.count' => 0.0010960102081299, 'insertInToLicenseRefTableUsingJson.insertInTolicense_ref_2' => 0.27189683914185, 'initLicenseRefTable.newLic' => 0.024376153945923, 'initLicenseRefTable.licenseRefByShortname' => 0.0011038780212402, 'isLicenseExists.license_candidate' => 0.00052118301391602, 'initLicenseRefTable.updateLicenseRef.spdxId' => 0.0017261505126953, 'insertNewLicense.insertNewLicense.returning:rf_pk' => 0.00027298927307129]; protected $queryCount = ['fo_libschema::addInheritedRelations' => 6, 'fo_libschema::addTables' => 6, 'fo_libschema::addViews' => 6, 'fo_libschema::addSequences' => 6, 'fo_libschema::addConstraints' => 6, 'fo_libschema::addIndexes' => 6, 'Fossology\Lib\Db\DbManager::createMap.sysconfig.variablename,conf_value' => 1, 'checkAuthorCtPkSequence' => 1, 'fo_libschema::applySchema.getTimeout' => 1, 'fo_libschema::dropViews' => 1, 'fo_libschema::applySchema.resetTimeout' => 1, 'license_ref.count' => 1, 'insertInToLicenseRefTableUsingJson.insertInTolicense_ref_2' => 661, 'initLicenseRefTable.newLic' => 1, 'initLicenseRefTable.licenseRefByShortname' => 2, 'isLicenseExists.license_candidate' => 1, 'initLicenseRefTable.updateLicenseRef.spdxId' => 1, 'insertNewLicense.insertNewLicense.returning:rf_pk' => 0]; private ${Fossology\Lib\Db\DbManager}transactionDepth = 1 }, $license = ['rf_shortname' => 'GPL-2.0-or-later', 'rf_text' => 'GNU GENERAL PUBLIC LICENSE\n\nVersion 2, June 1991\n\nCopyright (C) 1989, 1991 Free Software Foundation, Inc.\n\n51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA\n\nEveryone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed.\n\nPreamble\n\nThe licenses for most software are designed to take away your freedom to share and change it. By contrast, the GNU General Public License is intended to guarantee your freedom to share and change free software--to '..., 'rf_url' => 'https://www.gnu.org/licenses/old-licenses/gpl-2.0-standalone.html', 'rf_fullname' => 'GNU General Public License v2.0 or later', 'rf_notes' => 'This license was released: June 1991. This license identifier refers to the choice to use code under GPL-2.0-or-later (i.e., GPL-2.0 or some later version), as distinguished from use of code under GPL-2.0-only. The license notice (as seen in the Standard License Header field below) states which of these applies the code in the file. The example in the exhibit to the license shows the license notice for the "or later" approach.', 'rf_active' => 't', 'rf_text_updatable' => 'f', 'rf_detector_type' => '1', 'marydone' => 'f', 'rf_spdx_id' => 'GPL-2.0-or-later'], $wasCandidate = *uninitialized*) /usr/local/lib/fossology/fossinit.php:670


```

**Comment by shaheemazmalmmd** [comment]
More information: 
```
*** Failed to insert following licenses ***

GPL-2.0-or-later,GPL-1.0-or-later,GPL-3.0-or-later,LGPL-2.0-only,LGPL-2.0-or-later,LGPL-2.1-or-later,LGPL-3.0-or-later,AGPL-1.0-only,AGPL-3.0-only,GPL-2.0-only,LGPL-3.0-only,LGPL-2.1-only,GFDL-1.1-only,GFDL-1.2-only,GFDL-1.3-only,GPL-1.0-only,GPL-3.0-only,LGPL-2.1-or-later-KDE-exception,GFDL-1.1-invariants-or-later,GFDL-1.2-invariants-or-later,GFDL-1.2-no-invariants-or-later


```

**Comment by GMishx** [comment]
Please note that fixes for test cases is in #2368

**Review by shaheemazmalmmd — APPROVED** [review]
Code looks good. tested works as expected.

**Pull request merged**
