### PR TITLE
fix(deps): Fix dependencies for Debian Buster

### PR DESCRIPTION
**Pull request by GMishx**
## Description

Fix the dependencies for Debian Buster (10).

## How to test

1. Check if all the listed dependencies can be installed without conflicts on all supported distros (at least on stretch and buster).
1. Check if FOSSology can be compiled successfully.

### CODE REVIEW

**Comment by ag4ums** [comment]
composer is breaking while installing from source
image

**Comment by GMishx** [comment]
> composer is breaking while installing from source

This appears to be an issue with composer itself not being compatible with PHP 7.3. Try upgrading composer using `composer self-update` or manually installing it.

**Comment by ag4ums** [comment]
well then why not updating the composer in the utils/install_composer.sh

**Comment by GMishx** [comment]
> well then why not updating the composer in the utils/install_composer.sh

I have bumped the composer version to 1.9.0 in the latest commit.

I tested it with PHP 5.6, 7.1 and 7.3 and it worked without any issue. Can you please test now?

**Pull request merged**
