### PR TITLE
feat(api): modify /jobs and related endpoints

### LINKED ISSUE #1301: The FOSSology `/jobs` rest entpoint should contain more useful information
The `/jobs` endpoint does not contain useful information like
- kind of job
- is it already finished (i.e. status)
- how fast was it
- time of end
- dependencies
- ...

### Details

Currently (https://github.com/fossology/fossology/commit/69629cc1f45f2cbde7e1318dba8cf96a3ac3de8a) the request to `.../jobs` returns something like
```
$ curl -k -s -S -u fossy:fossy -X GET http://localhost:8081/repo/api/v1/jobs
[
[...]
  {                                                                                                                                                                                                                                                           
    "id": 17,                                                                                                                                                                                                                                                 
    "name": "zlib-1.2.11.tar.gz",                                                                                                                                                                                                                             
    "queueDate": "2019-03-09 17:37:46.174642+00",                                                                                                                                                                                                             
    "uploadId": 9,                                                                                                                                                                                                                                            
    "userId": 3,                                                                                                                                                                                                                                              
    "groupId": 3                                                                                                                                                                                                                                              
  },                                                                                                                                                                                                                                                          
  {                                                                                                                                                                                                                                                           
    "id": 18,                                                                                                                                                                                                                                                 
    "name": "zlib-1.2.11.tar.gz",                                                                                                                                                                                                                             
    "queueDate": "2019-03-09 17:43:16.34307+00",                                                                                                                                                                                                              
    "uploadId": 9,                                                                                                                                                                                                                                            
    "userId": 3,                                                                                                                                                                                                                                              
    "groupId": 3                                                                                                                                                                                                                                              
  },                                                                                                                                                                                                                                                          
  {                                                                                                                                                                                                                                                           
    "id": 19,                                                                                                                                                                                                                                                 
    "name": "zlib-1.2.11.tar.gz",                                                                                                                                                                                                                             
    "queueDate": "2019-03-09 17:57:53.938163+00",                                                                                                                                                                                                             
    "uploadId": 9,                                                                                                                                                                                                                                            
    "userId": 3,                                                                                                                                                                                                                                              
    "groupId": 3                                                                                                                                                                                                                                              
  },                                                                                                                                                                                                                                                          
  {                                                                                                                                                                                                                                                           
    "id": 20,                                                                                                                                                                                                                                                 
    "name": "zlib-1.2.11.tar.gz",                                                                                                                                                                                                                             
    "queueDate": "2019-03-09 19:11:10.174993+00",                                                                                                                                                                                                             
    "uploadId": 11,                                                                                                                                                                                                                                           
    "userId": 3,                                                                                                                                                                                                                                              
    "groupId": 3                                                                                                                                                                                                                                              
  }                                                                                                                                                                                                                                                           
] 
```
and also the detail request contains not more informations
```
$ curl -k -s -S -u fossy:fossy -X GET http://localhost:8081/repo/api/v1/jobs/17                                                                                                                                                                                                                        
{                                                                                                                                                                                                                                                             
  "id": 17,                                                                                                                                                                                                                                                   
  "name": "zlib-1.2.11.tar.gz",                                                                                                                                                                                                                               
  "queueDate": "2019-03-09 17:37:46.174642+00",                                                                                                                                                                                                               
  "uploadId": 9,                                                                                                                                                                                                                                              
  "userId": 3,                                                                                                                                                                                                                                                
  "groupId": 3                                                                                                                                                                                                                                                
}
```

### LINKED ISSUE #1800: Rest end point {{baseUrl}}/jobs?upload=16 providing wrong information
### Description

Rest end point {{baseUrl}}/jobs?upload=16 providing wrong information 

#### How to reproduce

- Upload a vcs / file 
- perform can 
- perform delete of upload 
when the upload is in process 
- Query for job status  {{baseUrl}}/jobs?upload=16 

It should provide proper information of each step, but it will override the status of each step with the latest step status.Check the JSON below 

#### Screenshots

```
[
    {
        "id": 18,
        "name": "wget",
        "queueDate": "2020-06-26 19:28:16.535386+00",
        "uploadId": "16",
        "userId": "3",
        "groupId": "3",
        "eta": 0,
        "status": "Processing"
    },
    {
        "id": 19,
        "name": "WLS",
        "queueDate": "2020-06-29 04:18:01.752964+00",
        "uploadId": "16",
        "userId": "3",
        "groupId": "3",
        "eta": 0,
        "status": "Processing"
    },
    {
        "id": 128,
        "name": "WLS",
        "queueDate": "2020-07-31 11:07:51.292989+00",
        "uploadId": "16",
        "userId": "3",
        "groupId": "3",
        "eta": 0,
        "status": "Processing"
    },
    {
        "id": 137,
        "name": "Delete",
        "queueDate": "2020-09-11 08:10:16.075719+00",
        "uploadId": "16",
        "userId": "3",
        "groupId": "3",
        "eta": 2275,
        "status": "Processing"
    }
]
```

### Versions

* FOSSology version 3.8.0-52-gd9f6f6753 (code revision d9f6f6)

### LINKED ISSUE #1972: Limiting job status scope to child jobs only
### Description

While testing PR #1955, found following thing.
For an upload, there are only 2 failed jobs (readmeoss and ojo) but the REST API says `"status": "Failed"` for every single job even when all child job has `"status": "Completed"`.

Maybe the `"status"` of a job can be limited only to its child jobs' statuses.

#### Screenshots

image
image

#### How to reproduce

1. In an upload, run an agent and kill it.
2. Run another agent for the same upload or download a report to create new job.
3. Check the jobs page in UI or GET data from `/jobs` endpoint.

### Versions

* Tested against #1955

### LINKED ISSUE #2514: Jobs
Modify my recent and all recent jobs to get all the required data for UI.

### PR DESCRIPTION
**Pull request by dvjsharma**
## Description

This PR aims to modify and enhance `/jobs` and related endpoints to contain more useful information.

### Changes

1. For every distinct job, the `/jobs` endpoint now includes all the associated child jobs along with their detailed information.

image

2. The job status of each parent job is confined to its child job scope exclusively. If any other child job fails for the same upload, it won't affect the status of current job.

image
image

3. Modified `openapiv2.yml` and `openapi.yml` files to reflect documentation changes.
## How to test

Make a 'GET' request to any of `/jobs`, `/jobs/id`, `/jobs/all` or `/jobs?upload=<id>` to view the modifications.

Tracked by #2514
fixes #1301 
fixes #1800 
fixes #1972 
closes #2514 

CC @GMishx @shaheemazmalmmd @dushimsam @soham4abc

### CODE REVIEW

**Comment by dvjsharma** [comment]
Need advice on how to fix the controller tests. By current modifications, I added a `addJobQueue()` method to append the child job queue to the job object. For tests, the primary method is to mock all the internal calls of `addJobQueue()` method, but the data returned by each call is very large hence not feasible to be written as an expected result.

CC @GMishx

**Comment by dvjsharma** [comment]
### UPDATE: Have added the following improvements-

1. Deprecated `/jobs/history` endpoint in version 2 since the same functionality can be achieved using `/jobs?upload=<uid>`.
2. Added time zone information in `jobQueue` -> `startTime` and `endTime`. Now the format is also similar to `queueDate`.
3. Replaced `userId` and `groupId` with `userName` and `groupName` in version 2. The same has been adopted by other endpoints in version 2.
4. The jobs are now sorted in descending order of `queueDate`. This has been done for both versions as it won't break anything and can be termed a bug.
5. The job status of each parent job is confined to its child job scope exclusively. This is also done for both versions, as it was termed a bug.

CC @GMishx @dushimsam

**Review by GMishx — APPROVED** [review]
Changes looks good.

**Review by GMishx — APPROVED** [review]
Tested, working as expected.

**Pull request merged**
