### PR TITLE
Add more templates to SPDX2 agent: DEP5 and SPDX2 Tag/Value

### PR DESCRIPTION
**Pull request by maximilianhuber**
This pullrequest closes the issues
* #510, since
 - it adds an new agent **dep5** which calls internally **spdx2** with the parameter `--outputFormat=dep5`
* #548, since
 - it adds an new agent **spdx2tv** which calls internally **spdx2** with the parameter `--outputFormat=spdx2tv`

This way of delegation has two advantages:
1. the pull request #538 is no longer necessary
2. `src/www/ui/ajax-showjobs.php` is able to show meaningfull information:
tmp

Both new agents are registered in the `Browse-Pfile` menu:
menu

#### Example
Using [time-1.7.tar.gz](http://mirror.sdunix.com/gnu/time/), suggested by @kestewart, the agents create the files which are listed in [this gist](https://gist.github.com/maximilianhuber/34333370dc34cbc76e43) (without any clearing).

#### TODO / IDEAS:
* rename **spdx2** to something more generic and create an new agent **spdx2** similar to the agents above
* accumulate the files in the **dep5** and use wildcards
* add tests similar to **spdx2** for **spdx2tv**

### CODE REVIEW

**Comment by bufferoverflow** [comment]
Awesome work! :cool:
I would suggest to rename the **spdx2** to **report** or **export**.

dep5 and spdx-rdf works fine

spdx-tv had the following issue
```
2015-11-18 10:27:27 spdx2tv [0] :: JOB[23].spdx2tv[32573.localhost]: "Caught exception while processing uploadId=3: Only variables can be assigned to. Unexpected token "operator" of value "in" ("name" expected) in "spdx2tv-document.twig" at line 35#0 /usr/local/share/fossology/vendor/twig/twig/lib/Twig/ExpressionParser.php(541): Twig_TokenStream->expect(5, NULL, 'Only variables ...')"
2015-11-18 10:27:27 spdx2tv [0] :: JOB[23].spdx2tv[32573.localhost]: "#1 /usr/local/share/fossology/vendor/twig/twig/lib/Twig/TokenParser/For.php(30): Twig_ExpressionParser->parseAssignmentExpression()"
2015-11-18 10:27:27 spdx2tv [0] :: JOB[23].spdx2tv[32573.localhost]: "#2 /usr/local/share/fossology/vendor/twig/twig/lib/Twig/Parser.php(184): Twig_TokenParser_For->parse(Object(Twig_Token))"
2015-11-18 10:27:27 spdx2tv [0] :: JOB[23].spdx2tv[32573.localhost]: "#3 /usr/local/share/fossology/vendor/twig/twig/lib/Twig/Parser.php(95): Twig_Parser->subparse(NULL, false)"
2015-11-18 10:27:27 spdx2tv [0] :: JOB[23].spdx2tv[32573.localhost]: "#4 /usr/local/share/fossology/vendor/twig/twig/lib/Twig/Environment.php(615): Twig_Parser->parse(Object(Twig_TokenStream))"
2015-11-18 10:27:27 spdx2tv [0] :: JOB[23].spdx2tv[32573.localhost]: "#5 /usr/local/share/fossology/vendor/twig/twig/lib/Twig/Environment.php(667): Twig_Environment->parse(Object(Twig_TokenStream))"
2015-11-18 10:27:27 spdx2tv [0] :: JOB[23].spdx2tv[32573.localhost]: "#6 /usr/local/share/fossology/vendor/twig/twig/lib/Twig/Environment.php(396): Twig_Environment->compileSource('{# Copyright 20...', 'spdx2tv-documen...')"
2015-11-18 10:27:27 spdx2tv [0] :: JOB[23].spdx2tv[32573.localhost]: "#7 /usr/local/share/fossology/spdx2/agent/spdx2.php(414): Twig_Environment->loadTemplate('spdx2tv-documen...')"
2015-11-18 10:27:27 spdx2tv [0] :: JOB[23].spdx2tv[32573.localhost]: "#8 /usr/local/share/fossology/spdx2/agent/spdx2.php(396): Fossology\SpdxTwo\SpdxTwoAgent->renderString('spdx2tv-documen...', Array)"
2015-11-18 10:27:27 spdx2tv [0] :: JOB[23].spdx2tv[32573.localhost]: "#9 /usr/local/share/fossology/spdx2/agent/spdx2.php(143): Fossology\SpdxTwo\SpdxTwoAgent->writeReport('?PackageName: t...', Array, 3)"
2015-11-18 10:27:27 spdx2tv [0] :: JOB[23].spdx2tv[32573.localhost]: "#10 /usr/local/share/fossology/lib/php/Agent/Agent.php(205): Fossology\SpdxTwo\SpdxTwoAgent->processUploadId(3)"
2015-11-18 10:27:27 spdx2tv [0] :: JOB[23].spdx2tv[32573.localhost]: "#11 /usr/local/share/fossology/spdx2/agent/spdx2.php(536): Fossology\Lib\Agent\Agent->run_scheduler_event_loop()"
2015-11-18 10:27:27 spdx2tv [0] :: JOB[23].spdx2tv[32573.localhost]: "#12 /usr/local/lib/fossology/fo_wrapper(77): require('/usr/local/shar...')"
2015-11-18 10:27:27 spdx2tv [0] :: JOB[23].spdx2tv[32573.localhost]: "#13 {main}agent failed on uploadId=3#0  Fossology\Lib\Agent\Agent->bail() called at [/usr/local/share/fossology/lib/php/Agent/Agent.php:217]"
2015-11-18 10:27:27 spdx2tv [0] :: JOB[23].spdx2tv[32573.localhost]: "#1  Fossology\Lib\Agent\Agent->run_scheduler_event_loop() called at [/usr/local/share/fossology/spdx2/agent/spdx2.php:536]"
2015-11-18 10:27:27 spdx2tv [0] :: JOB[23].spdx2tv[32573.localhost]: "#2  require(/usr/local/share/fossology/spdx2/agent/spdx2.php) called at [/usr/local/lib/fossology/fo_wrapper:77]"
2015-11-18 10:27:27 spdx2tv [0] :: JOB[23].spdx2tv[32573.localhost]: agent failed with error code 1
2015-11-18 10:27:28 spdx2tv [0] :: JOB[23].spdx2tv[32573.localhost]: agent failed, code: 0
```

I used the vagrant environment and time-1.7 for testing

**Comment by maximilianhuber** [comment]
Thanks for mentioning this. It was a stupid copy-and-paste bug.

**Comment by maximilianhuber** [comment]
#### The reason, why i have not yet renamed the spdx2-agent:
if one updates the sources and then issues a `sudo make install` one has the PHP-files in both folders `spdx2/ui` and `report/ui` and since they define the same PHP-classes. This results in an fatal error. Further will `sudo make uninstall; sudo make install` maybe not solve this problem, since the new and adapted Makefile might not clean `spdx2/ui/*.php`

#### Possible solutions:
* clean old installation for every `sudo make install`
* keep old `uninstall`-part in the Makefile

I am not yet shure, how to do this in a clean way.

**Comment by kestewart** [comment]
This is excellent! :+1:

The "select action" button on the browse,  implies that there should probably be an action on the pull down, so having **export** in front of the formats FOSSology is able to generate, would make it clearer what's happening.    The current options might then look something like:

* export ReadMe_OSS
* export DEP5
* export SPDX tag:value
* export SPDX RDF

Do you think this would help?

**Comment by maximilianhuber** [comment]
it now looks like:
menu

(i have overlooked, that you suggested to change `SPDX2`->`SPDX` and `Tag/Value`->`tag:value`, this will be done with the next commit)

**Comment by bufferoverflow** [comment]
:+1:  local test passed, I would say merge to master

**Pull request merged**
