### PR TITLE
fix(testCases): Fix scheduler and ununpack test cases

### PR DESCRIPTION
**Pull request by GMishx**
**Changes:**

1.  Can directly call `make test` from top directory to test every agent.
2.  Prevent printing VERSION file command.
3.  Change LLVM repository from precise to trusty.
4.  Changes suggested by clang-7 (C++17):
>  Removed call to move for copy elision.
>  copyright_error
>  wget_error

**How to test:**

1.  Make directory `/srv/fossologyTestRepo` and give permission to current user:
```
sudo mkdir -p /srv/fossologyTestRepo
sudo chown $(whoami) /srv/fossologyTestRepo
```
2.  Create `fossologytest` and `fossy` user in PostgreSQL and save their passwords in `~/.pgpass`.
```
psql -c "CREATE USER fossy WITH CREATEDB LOGIN PASSWORD 'fossy';" -U postgres
psql -c "CREATE USER fossologytest WITH CREATEDB LOGIN PASSWORD 'fossologytest';" -U postgres
echo "localhost:*:*:fossy:fossy" >> ~/.pgpass
echo "localhost:*:*:fossologytest:fossologytest" >> ~/.pgpass
chmod 0600 ~/.pgpass
```
3.  Install composer dependencies
```
cd src && composer install
```
4.  Run `make all test`
5.  Install cppcheck `sudo apt-get install cppcheck`.
6.  Run `cppcheck -q -isrc/nomos/agent_tests/testdata/NomosTestfiles/ -isrc/testing/dataFiles/ --suppress=*:src/copyright/agent/json.hpp src/`

### CODE REVIEW

**Comment by GMishx** [comment]
Unfortunately, I am not able to run clang-6.0, clang-7, clang++-6.0 and clang++-7 on Ubuntu Trusty.
Anyone have a good suggestion on it so that new clang tests can also be included here (they have C++17 standard as default).
The error I am getting is with OpenMP. Have created an issue at [llvm.org](https://bugs.llvm.org/show_bug.cgi?id=37322).

**Comment by ag4ums** [comment]
copyright functional test failing 
image

**Comment by ag4ums** [comment]
functional test  error seems to be a configuration issue in local system

**Comment by GMishx** [comment]
Are you running tests as sudo?

**Comment by ag4ums** [comment]
though not failing in travis but seems there are some problem with unpack test:
image

**Comment by GMishx** [comment]
This problem might be due to #61 
Ununpack agent needs a rework.

**Comment by maxhbr** [comment]
Due to pull request, one needs `sudo` for `make test`. This is not acceptable.
Also not acceptable is that the script `utils/prepare-test`, if someone calls `make test` (e.g. on a productive system), creates a test user with a fixed password in a potential productively used and exposed database.

Further does the script `utils/prepare-test` add two lines to the `~/.pgpass` for every call of `make test`.

Further does the line `sudo chown $(whoami) /var/local/cache/fossology` in the  `utils/prepare-test` script break the fossology instance, if `make test` is called as other user than fossy.

**Comment by maxhbr** [comment]
This also reenables the blinking test. Travis now fails again randomly

**Pull request merged**
