### PR TITLE
fix #406 and add groupname option to cp2foss

### LINKED ISSUE #406: cp2foss fails to run after 2.6
larry is working on it.

### PR DESCRIPTION
**Pull request by steffen-weber**
fix #406 and add groupname option to cp2foss

### CODE REVIEW

**Comment by pguttmann** [comment]
You may wish to confirm that your change to account_check gets addressed in various other cli files that may be impacted by your change ;)

ubuntu@foss262demo:~/fossology$ grep -r 'account_check' .
./src/lib/php/common-auth.php:function account_check(&$user, &$passwd)
./src/cli/fossjobs.php:account_check($user, $passwd); // check username/password
./src/cli/cp2foss.php:account_check($user, $passwd); // check username/password
./src/cli/fo_bucket_list.php:account_check($user, $passwd); // check username/password
./src/cli/fo_copyright_list.php:account_check($user, $passwd); // check username/password
./src/cli/fo_nomos_license_list.php:account_check($user, $passwd); // check username/password

**Comment by steffen-weber** [comment]
Since $group is only an optional argument in account_check, the call ```account_check($user, $passwd)``` behaves as before.

**Comment by pguttmann** [comment]
Ah, ok - so by assigning a "default value" to that argument in the function definition it becomes "optional" I guess.

**Comment by joshovi** [comment]
Merged this in hope that this will fix Paul's tickets.

**Pull request merged**
