### PR TITLE
fix(licenses): revert merging of #883

### PR DESCRIPTION
**Pull request by max-wittig**
Comment characters in the MPL-2.0 are actually there on purpose:
https://www.mozilla.org/media/MPL/2.0/index.815ca599c9df.txt

### CODE REVIEW

**Comment by maxhbr** [comment]
@mcjaeger This PR correctly reverts #883 and can be merged

**Comment by maxhbr** [comment]
The tests fail due to the conventional change log test

##
#### off topic:
@max-wittig in the conventional changelog test the log states that the used application is deprecated and `commitlint` should be used instead.

**Comment by max-wittig** [comment]
@maxhbr You're right. I'm gonna prepare a PR for updating this.

**Comment by mcjaeger** [comment]
seems like the change of the license files does change the bahaviour of the (C-based) tests of nomos and monk, as the monk test fails in several builds  

```
1) MonkScheduledTest::testRunMonkScan
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
     0 => Fossology\Lib\Data\Highlight Object (
         'start' => 18
         'end' => 35825
         'type' => 'M'
-        'licenseId' => 385
+        'licenseId' => '385'
         'refStart' => 20
-        'refEnd' => 35819
+        'refEnd' => 35146
         'infoText' => ''
         'htmlElement' => null
     )
 )
```

**Comment by mcjaeger** [comment]
I am sceptical about this PR because it says for the licenseref diff:
```
43,497 additions, 43,268 deletions not shown because the diff is too large. Please use a local Git client to view these changes.
```

**Comment by mcjaeger** [comment]
we are not getting progress since longer time here and this PR is not good for merging:

https://github.com/fossology/fossology/issues/934

**Pull request closed without merging**
