### PR TITLE
chore(composer): update composer form 1.9.0 to 2.2.6 version

### PR DESCRIPTION
**Pull request by shaheemazmalmmd**
### Changes

Update version and hash to version2.26

## How to test

* Install fossology with utils/fo-installdeps
* Check composer version using "**composer about**"
* Check if everything works on UI like report, clearing etc..

<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2159"></a>

### CODE REVIEW

**Review by GMishx — APPROVED** [review]
Changes looks good.

**Review by GMishx — APPROVED** [review]
Tested, working as expected.

**Comment by GMishx** [comment]
@shaheemazmalmmd , can we instead add `composer` as a dependency in `apt`/`yum` list? It will solve the issue #692 and make packaging easier.

**Comment by shaheemazmalmmd** [comment]
> @shaheemazmalmmd , can we instead add `composer` as a dependency in `apt`/`yum` list? It will solve the issue #692 and make packaging easier.

Good amount of changes and testing needs to be done. can we take this PR and add the changes to some other PR.

**Pull request merged**
