### PR TITLE
fix(src/ununpack/agent/utils.c) attempt to escape correct characters in filenames

### LINKED ISSUE #1397: Unpack failure when a filename contains single quotes
### Description

Unpack failure when a filename contains the character `'`.

#### How to reproduce

1. Upload a package containing a file with a quote in its name (eg. `foo'bar.baz`)
1. The Unpack stage will fail with following logs:
```
2019-07-09 12:49:12 ununpack [0] :: JOB[102].ununpack[1621.localhost]: "sh: 1: Syntax error: Unterminated quoted string"
2019-07-09 12:49:12 ununpack [0] :: JOB[102].ununpack[1621.localhost]: "FATAL utils.c.1585: Unable to calculate SHA256 of /srv/fossology/repository/6764497f58c4/ununpack/469540l/94c2650a0e7a9b7b7ad839860ccb1d9231232b4c.7475b9a3872350af0d2c2300446b0445.240.dir/upload_01.dir/upload_01/foo'bar.baz"
2019-07-09 12:49:12 ununpack [0] :: JOB[102].ununpack[1621.localhost]: agent failed with error code 56
2019-07-09 12:49:12 ununpack [0] :: JOB[102].ununpack[1621.localhost]: agent failed, code: 56
```

The problem come from this line, as the filename is included unprotected:
https://github.com/fossology/fossology/blob/a26c0cd8ec0dca5063248667d734f86cc5c23f08/src/ununpack/agent/utils.c#L1576

Replacing single quotes fixes with `"sha256sum \"%s\""` fixes the single-quote problem, but of course now it fails with filenames containing double quotes :)

I don't know if there is already an escape function available in the source code to reuse ; but I'll look for a quick workaround for now.

#### Screenshots

image

### Versions

* Last commit id on master: https://github.com/fossology/fossology/commit/53849883c7a95f699f8b2198a1849aa6926dee6f
* Operating System (lsb_release -a): Docker build

### PR DESCRIPTION
**Pull request by NicolasToussaint**
Fixes #1397 

## Description

Enclosing the filenames in single quotes, and escaping the existing single quotes do not work, somehow (in my Docker environment).
I had to enclose in double quotes and escape `"`, `\` and `$`.

The fix works fine, except for filenames containing '\' characters, see #1397 
I also make additional checks on filename length that were missing before.

### Changes

I copy the filename, character by character, escaping ", \ and $, to the new array, checking for array size.

In the changes, I am not sure which exit code should be used if the (escaped) filename length exceeds the array length.

## How to test

Uploaded a package with the following files ; all but those with `\` are unpacked:
image

### CODE REVIEW

**Comment by mcjaeger** [comment]
@NicolasToussaint in case you can share the package for testing, pls feel free to send it

**Comment by NicolasToussaint** [comment]
@mcjaeger , I sure will ; I also need to look into the unit tests.

For the time being, I'm looking at another approach, as discussed in the issue https://github.com/fossology/fossology/issues/1397

**Comment by NicolasToussaint** [comment]
I got a working solution, just added it to the merge request.

A few comments:
- the SHA256 implementation comes from [ckolivas/cgminer](https://github.com/ckolivas/cgminer) (more precisely, [sha2.h](https://github.com/ckolivas/cgminer/blob/master/sha2.h) and [sha2.c](https://github.com/ckolivas/cgminer/blob/master/sha2.c))
- No modification was made to the sources (appart from commenting out some `#include`)
- The sources look like _BSD-3-Clause_ (accoring to Nomos)
- I had to add the `-fPIC` option (see [GCC doc](http://gcc.gnu.org/onlinedocs/gcc/Code-Gen-Options.html#Code-Gen-Options)) to the `CFLAGS` variable, in the topmost `Makefile.conf` - otherwise the build fails. I'm not sure if it's a problem for the Fossology project.
- I tested with this package containing the filenames below, as well as more classic packages.
   - [Issue_1397.zip](https://github.com/fossology/fossology/files/3477871/Issue_1397.zip)
```
upload_02/
upload_02/double"""quotes-01
upload_02/'_________first.zoz
upload_02/last__________.zoz'
upload_02/'_'_'_'_'_'_'_'_'_'_'''''''____'_'_'_'_''___multiple'.'z'o'z
upload_02/"__"_"_"_"_"""""===""$"$"$"$"$=="______"$\\
upload_02/file_01
upload_02/exc!!!amation, spaces, and %%%% $hara$ters
upload_02/__"_"_"_"_""""=x=""$"$"$"$"$=="_''''_'_'_''__''f
upload_02/"double-quotes
upload_02/foo'bar.baz
upload_02/"__"_"_"_"_"""""===""$"$"$"$"$=="______"$\\\\\\
upload_02/double-quotes"
upload_02/__"_"_"_"_""""=x=""$"$"$$"$=="______"$\\f
upload_02/$$dollar_$_rallod$$
```
- The Unpack goes well, the SHA256SUMS are correct
- I didn't add a unit test (yet) (here? [src/ununpack/agent_tests](https://github.com/fossology/fossology/tree/master/src/ununpack/agent_tests))
- I left some `#define NEW_SHA256SUM` lying around, I (of course) intend to clean this up when all is OK

And I'm not sure how and where the credits for the original source code should be mentioned.

**Comment by NicolasToussaint** [comment]
Actually, the original source code comes from here: [ouah.org/ogay/sha2](http://ouah.org/ogay/sha2/) / [github.com/ouah/sha2](https://github.com/ouah/sha2).

It is distributed under the BSD licence.

**Comment by NicolasToussaint** [comment]
Sorry, this PR became a mess, and I don't know how to make this look clean in GitHub.
I created a new PR https://github.com/fossology/fossology/pull/1425
Closing this one.

**Pull request closed without merging**
