### PR TITLE
./delagent fixes #271 and #272

### LINKED ISSUE #271: a none permission user can get an upload list via /delagent  -f
---

Author Name: **larry shi** 
Original Redmine Issue: 6729, http://www.fossology.org/issues/6729
Original Date: 2014/03/18
Original Assignee: Dong Ma

---

larry@bl460c-10:~/fossology/src/delagent/agent$ ./delagent  --user t2 --password '' -f
1. Folders
   1 :: Software Repository
     -- :: Contains: fossology_2.4.0-1.tar.gz
     -- :: Contains: fossology_2.4.0-1.tar.gz
     -- :: Contains: fossology-buckets-2.4.0-1.el6.x86_64.rpm
     -- :: Contains: fossology.git
     -- :: Contains: grit.git
     -- :: Contains: *.php
     -- :: Contains: *.php
     -- :: Contains: *.php
     -- :: Contains: *.php
     -- :: Contains: *.php
     -- :: Contains: *.rpm
     -- :: Contains: schema-export.php
     -- :: Contains: schema-export.php
     -- :: Contains: test
     -- :: Contains: test
     -- :: Contains: test
     -- :: Contains: test
     -- :: Contains: test
     -- :: Contains: test
     -- :: Contains: test
     -- :: Contains: test
     -- :: Contains: test
     -- :: Contains: test
     -- :: Contains: test
     -- :: Contains: test
      3 :: tests250
         4 :: command
           -- :: Contains: *.deb
        -- :: Contains: fossology-buckets-2.4.0-1.el6.x86_64.rpm

### PR DESCRIPTION
**Pull request by shaheemazmalmmd**
#271 :: a none permission user can get an upload list via /delagent -f  

#272 :: any user who is not the owner can delete any upload via /delagent -U  :: fixed with only owners and group admins can delete the upload now.

### CODE REVIEW

**Comment by maximilianhuber** [comment]
Hi Shaheem,

I have build your branch with vagrant and I have tried the example mentioned in #271 and got an "Segmentation fault":
tmp

The reason seams to be, that the user **t2** does not exist on my system. With the user **fossy** and empty resp. correct password I get the expected behaviour:
tmp

**Comment by shaheemazmalmmd** [comment]
Hello Maximilian,
The same behavior exists in master as well. shall i fix this here ??

**Comment by maximilianhuber** [comment]
Yes, this might be the right place to add this fix.

Do you also want to tackle #273?

**Comment by shaheemazmalmmd** [comment]
Ok i will push the change here. fix for 273 is not available here. in this pull.

**Pull request merged**
