### PR TITLE
feat(upload): add tooltips and description to individual agents

### PR DESCRIPTION
**Pull request by shaheemazmalmmd**
## Description

add tooltips and description to individual agents.

## How to test

* Install fossology and check if tooltip works in all upload pages.

### CODE REVIEW

**Review by GMishx — APPROVED** [review]
Changes looks good.

**Review by GMishx — CHANGES_REQUESTED** [review]
The HTML part of agent Title renders like following on Job > Schedule Agents page.

image

**Comment by shaheemazmalmmd** [comment]
@GMishx : Thanks for pointing. fixed applied.

**Review by GMishx — APPROVED** [review]
Changes looks good.

**Review by GMishx — APPROVED** [review]
Tested, working as expected.

**Pull request merged**
