### PR TITLE
feat(ubuntu): support ubuntu jammy 22.04 for fossology

### PR DESCRIPTION
**Pull request by shaheemazmalmmd**
## Description

Add support for ubuntu jammy 22.04 for fossology.

### Changes

added jammy support in installdeps file and corrected a warning.

## How to test

* Test every functionality of fossology using source install as well as debian install in Ubuntu 22.04

<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2300"></a>

### CODE REVIEW

**Review by GMishx — APPROVED** [review]
Changes look good.

**Comment by shaheemazmalmmd** [comment]
@GMishx Thanks for pointing. Changes Done 👍

**Comment by GMishx** [comment]
Oops, looks like you missed changing `src/ojo/mod_deps`
```diff
diff --git a/src/ojo/mod_deps b/src/ojo/mod_deps
index c7134bd74..221f47922 100755
--- a/src/ojo/mod_deps
+++ b/src/ojo/mod_deps
@@ -101,6 +101,8 @@ if [[ $RUNTIME ]]; then
           apt-get $YesOpt install libjsoncpp1 libboost-filesystem1.71.0 libboost-program-options1.71.0 libboost-regex1.71.0;;
         focal)
           apt-get $YesOpt install libjsoncpp25 libboost-filesystem1.74.0 libboost-program-options1.74.0 libboost-regex1.74.0;;
+       jammy)
+          apt-get $YesOpt install libjsoncpp25 libboost-filesystem1.74.0 libboost-program-options1.74.0 libboost-regex1.74.0;;
         *) echo "ERROR: Unknown or Unsupported $DISTRO $CODENAME release, please report to the mailing list"; exit 1;;
       esac;;
     Fedora)
```

**Comment by GMishx** [comment]
Also, somehow scheduler is not able to read the `fossology.conf` file. I am not sure it is some issue with my setup or in the code.

```
$ sudo service fossology start
Starting FOSSology job scheduler: 2022-08-31 14:23:09 initializing [99045] :: FATAL scheduler.c.872: /usr/local/etc/fossology/fossology.conf[line 1]: incorrectly formated line "".
2022-08-31 14:23:09 initializing [99045] :: FATAL errno is: Success
```

**Comment by shaheemazmalmmd** [comment]
> Oops, looks like you missed changing `src/ojo/mod_deps`
> 
> ```diff
> diff --git a/src/ojo/mod_deps b/src/ojo/mod_deps
> index c7134bd74..221f47922 100755
> --- a/src/ojo/mod_deps
> +++ b/src/ojo/mod_deps
> @@ -101,6 +101,8 @@ if [[ $RUNTIME ]]; then
>            apt-get $YesOpt install libjsoncpp1 libboost-filesystem1.71.0 libboost-program-options1.71.0 libboost-regex1.71.0;;
>          focal)
>            apt-get $YesOpt install libjsoncpp25 libboost-filesystem1.74.0 libboost-program-options1.74.0 libboost-regex1.74.0;;
> +       jammy)
> +          apt-get $YesOpt install libjsoncpp25 libboost-filesystem1.74.0 libboost-program-options1.74.0 libboost-regex1.74.0;;
>          *) echo "ERROR: Unknown or Unsupported $DISTRO $CODENAME release, please report to the mailing list"; exit 1;;
>        esac;;
>      Fedora)
> ```

added duplicate to focal it should be jammy.

**Comment by GMishx** [comment]
The library is apparently sending empty content for regex match group in Ubuntu Jammy which is causing the issue. Following patch should capture such empty strings:

```diff
diff --git a/src/lib/c/fossconfig.c b/src/lib/c/fossconfig.c
index 588a4d863..7e1131938 100644
--- a/src/lib/c/fossconfig.c
+++ b/src/lib/c/fossconfig.c
@@ -207,11 +207,18 @@ static gboolean fo_config_eval(const GMatchInfo* match, GTree** g_current,
   /* check to make sure we haven't hit an error */
   if ((error_t = g_match_info_fetch_named(match, "error")) != NULL)
   {
-    g_set_error(error, PARSE_ERROR, fo_invalid_file,
-      "%s[line %d]: incorrectly formated line \"%s\".",
-      yyfile, yyline, error_t);
-    g_free(error_t);
-    return TRUE;
+    if (strlen(error_t) > 0)
+    {
+      g_set_error(error, PARSE_ERROR, fo_invalid_file,
+        "%s[line %d]: incorrectly formated line \"%s\".",
+        yyfile, yyline, error_t);
+      g_free(error_t);
+      return TRUE;
+    }
+    else
+    {
+      g_free(error_t);
+    }
   }
 
   gchar* group = g_match_info_fetch_named(match, "group");
```

**Review by GMishx — APPROVED** [review]
Tested, working as expected.

**Pull request merged**
