### PR TITLE
(feat) docker services healthchecks in the docker-compose file

### PR DESCRIPTION
**Pull request by NicolasToussaint**
## Description

Use the [Health-check](https://github.com/compose-spec/compose-spec/blob/master/spec.md#healthcheck) feature inside `docker-compose` files to have a quick heath status of the containers when running `docker status`

### Changes

Proposed health tests are:
- *web* : `test: ["CMD-SHELL", "curl -sSf localhost/repo/api/v1/version || exit 1"]`
- *database* : `test: ["CMD-SHELL", "pg_isready"]`
- *scheduler* : `test: ["CMD-SHELL", "true"]`
   - **-> did not find a really useful check here since the container crashes as it becomes unhealthy!**

That's a first shot, tests can be improved in the future.

## How to test

1. Run Fossology using provided docker-compose file
2. Run `docker container ls -a`
image

### CODE REVIEW

**Review by GMishx — APPROVED** [review]

**Comment by GMishx** [comment]
Thank you for the contribution @NicolasToussaint . Can you please update the commit message to be more aligned with contributing guidelines?

**Comment by GMishx** [comment]
How about using `pg_isready --dbname $$POSTGRES_DB --username $$POSTGRES_USER` as the health check for DB container? I am getting following message in the DB logs which is hard to understand sometimes.
image

**Comment by NicolasToussaint** [comment]
> Thank you for the contribution @NicolasToussaint . Can you please update the commit message to be more aligned with contributing guidelines?

My pleasure of course :)
Sorry for the wrong message, I'll fix it

**Review by GMishx — APPROVED** [review]
Tested, working as expected.

**Pull request merged**
