### PR TITLE
feat(gdpr) New global option to make all user details read-only

### PR DESCRIPTION
**Pull request by NicolasToussaint**
## Description

A new option in the Customize page make all user details read-only (Username, email, Description)
Useful when details are retrieved from external auth server and should never be altered by hand.

### Changes

New option in Customize page 
image

## How to test

Create User, details are editable
image

Go to Admin -> Customize, down the page, click on `Make account details read-only`
image

Check value in database:
```
fossology=# select variablename,conf_value from sysconfig where variablename='UserDescReadOnly';
   variablename   | conf_value 
------------------+------------
 UserDescReadOnly | true
(1 row)
```

Accounts become read-only
image

Operation is reversible.

### CODE REVIEW

**Comment by NicolasToussaint** [comment]
Arg, my mistake : we actually identified this bug and realized that the fields should be tagged as _readonly_ (with `readonly="true"`) rather than disabled

image

That make the fields RO while preserving data when posting

**Comment by NicolasToussaint** [comment]
Proposed this fix: https://github.com/fossology/fossology/pull/2137/commits/0c901c4b9a90a1880165eca31c23fdbfee87f4e8

Meaning that maybe the other fix https://github.com/fossology/fossology/pull/2118/commits/36a1573aee1e0633213986b152ef3d6b31fa7a21 can be reverted ?

If OK, I can propose yet anotyher PR because I think I messed the Git Log :-/

**Comment by GMishx** [comment]
> Proposed this fix: 0c901c4b9a90a1880165eca31c23fdbfee87f4e8

Looks good. I missed the `readonly` attribute :-)

> Meaning that maybe the other fix 36a1573aee1e0633213986b152ef3d6b31fa7a21 can be reverted ?

Agree. Would you like to that in this PR or a separate one?

**Comment by NicolasToussaint** [comment]
OK good ;
I will prepare a separate fresh PR

**Pull request closed without merging**
