### PR TITLE
update(org): upgraded php version to php7

### PR DESCRIPTION
**Pull request by sjha2048**
## Description
upgraded php version to 7.0.8

Part of #1760
Previous Conversation: #1765

### CODE REVIEW

**Comment by GMishx** [comment]
Got following errors while testing. Please fix:

#### Upload >> Upload from Version Control
```
PHP Fatal error:  Uncaught Error: Call to undefined method Twig\\Environment::clearTemplateCache() in /usr/local/share/fossology/www/ui/page/UploadVcsPage.php:56\nStack trace:
#0 /usr/local/share/fossology/www/ui/page/UploadPageBase.php(102): Fossology\\UI\\Page\\UploadVcsPage->handleView()
#1 /usr/local/share/fossology/lib/php/Plugin/DefaultPlugin.php(239): Fossology\\UI\\Page\\UploadPageBase->handle()
#2 /usr/local/share/fossology/lib/php/Plugin/DefaultPlugin.php(271): Fossology\\Lib\\Plugin\\DefaultPlugin->getResponse()
#3 /usr/local/share/fossology/www/ui/index.php(64): Fossology\\Lib\\Plugin\\DefaultPlugin->execute()
#4 {main}
  thrown in /usr/local/share/fossology/www/ui/page/UploadVcsPage.php on line 56, referer: http://localhost/repo/?mod=upload_url
```

#### Upload >> Instructions
```
PHP Fatal error:  Uncaught Error: Call to undefined method Twig\\Environment::clearTemplateCache() in /usr/local/share/fossology/www/ui/upload-instructions.php:45
Stack trace:
#0 /usr/local/share/fossology/lib/php/Plugin/DefaultPlugin.php(239): UploadInstructions->handle()
#1 /usr/local/share/fossology/lib/php/Plugin/DefaultPlugin.php(271): Fossology\\Lib\\Plugin\\DefaultPlugin->getResponse()
#2 /usr/local/share/fossology/www/ui/index.php(64): Fossology\\Lib\\Plugin\\DefaultPlugin->execute()
#3 {main}
  thrown in /usr/local/share/fossology/www/ui/upload-instructions.php on line 45, referer: http://localhost/repo/?mod=ui_reportImport
```

#### Admin > License admin > Select license
Please apply following escaping as special characters in obligation text is breaking the view:
```diff
diff --git a/src/www/ui/template/admin_license_file.js.twig b/src/www/ui/template/admin_license_file.js.twig
index c14e0fe2a..5e98b5fa7 100644
--- a/src/www/ui/template/admin_license_file.js.twig
+++ b/src/www/ui/template/admin_license_file.js.twig
@@ -51,7 +51,7 @@ function getDataForTable() {
     "rf_fullname":        "{{ entry['rf_fullname']|escape('js') }}",
     "rf_text":            [ "{{ entry['rf_pk'] }}", "{{ entry['rf_text'][:120]|escape('js') }}" ],
     "rf_url":             "{{ entry['rf_url'] }}",
-    "ob_topic":           "{{ entry['ob_topic'] }}"
+    "ob_topic":           "{{ entry['ob_topic']|escape('js') }}"
   });
   {% endfor %}
```

#### In an upload > Info page
```
PHP Fatal error:  Uncaught Exception: Missing upload tree parent for upload in /usr/local/share/fossology/lib/php/Dao/UploadDao.php:311
Stack trace:
#0 /usr/local/share/fossology/www/ui/ui-view-info.php(543): Fossology\\Lib\\Dao\\UploadDao->getUploadParent()
#1 /usr/local/share/fossology/www/ui/ui-view-info.php(569): ui_view_info->showReuseInfo()
#2 /usr/local/share/fossology/lib/php/Plugin/FO_Plugin.php(383): ui_view_info->Output()
#3 /usr/local/share/fossology/lib/php/Plugin/FO_Plugin.php(467): FO_Plugin->getResponse()
#4 /usr/local/share/fossology/www/ui/index.php(64): FO_Plugin->execute()
#5 {main}
  thrown in /usr/local/share/fossology/lib/php/Dao/UploadDao.php on line 311, referer: http://localhost/repo/?mod=license&upload=163&folder=6&item=311380&show=quick
```

There is one more issue with the Upload's conf page, but it will be solved by #1802

**Comment by sjha2048** [comment]
Is this patch going to fix the above errors?
I have updated the pr.

**Comment by GMishx** [comment]
The patch was to fix only the License list page. For others, we need to find the cause and fix it. I just provided the stack trace here.

**Comment by sjha2048** [comment]
Understood

**Review by GMishx — APPROVED** [review]
Changes looks good. Needs another round of testing.

**Review by GMishx — APPROVED** [review]
Tested, working fine.

**Pull request merged**
