### PR TITLE
Scanoss qg/2668/row number out of range

### PR DESCRIPTION
**Pull request by scanoss-qg**
## Description
Fixes a weird logged error on the upload

### Changes
- Fixes the error reported on log file
"row number 0 is out of range 0..-1"
- Restore snippet matching view (some external modification on the code leads to not showing the table)
- Removes agent temp folder used on a scan
- Fixed some conditions that could lead to segfault

## How to test
- Upload https://github.com/fossology/atarashi/ master.
- Schedule SCANOSS agent.
- Go to upload logs
- Check that "row number 0 is out of range 0..-1" does not exist anymore

### CODE REVIEW

**Comment by shaheemazmalmmd** [comment]
@scanoss-qg : Thank you for your contribution. can you please squash your commits to one ?? and also add the commit message according to our [contributing](https://github.com/fossology/fossology/blob/master/CONTRIBUTING.md) guidelines?

**Comment by scanoss-qg** [comment]
@shaheemazmalmmd I think PR is now in order!

**Comment by GMishx** [comment]
Hi @scanoss-qg , for the #2818 to be considered done, the agent should read the `http_proxy` and `https_proxy` from the `/etc/fossology/fossology.conf` and use them for creating connection with osskb.org.

You can refer to following C code for reference how to read values from the conf file.
https://github.com/fossology/fossology/blob/983ef69332504d361da09231278a6a7fac466d66/src/wget_agent/agent/wget_agent.c#L916-L970

**Review by shaheemazmalmmd — APPROVED** [review]
Code looks good. Works as expected.

**Pull request merged**
