### PR TITLE
chore: refactor dockerfiles

### PR DESCRIPTION
**Pull request by bufferoverflow**
- the dockerfile commands were reordered to prevent unnecessary rebuilds
- the repository is now a volume
- the containers run now unpriviledged
- some commands were moved from the entrypoint to the Dockerfile
- the docker-compose file is now `version: 2`

### CODE REVIEW

**Comment by maximilianhuber** [comment]
@bufferoverflow thank you for rebasing. I hope that this PR gets merged, soon.

**Comment by bufferoverflow** [comment]
@maximilianhuber @steffen-weber @mcjaeger could some of you merge this please?

**Comment by maximilianhuber** [comment]
@bufferoverflow This implies that the PR is approved by you?

**Comment by bufferoverflow** [comment]
I can't approve by ui because I made the PR, so take this as approval.

**Pull request merged**
