### PR TITLE
fix(obligations): reintegrate lost changes

### PR DESCRIPTION
**Pull request by deveaud-m**
Use correct copyright year for last changes.
Set filename while exporting the obligations CSV.
Allow obligations with no licenses associated.

### CODE REVIEW

**Comment by shaheemazmalmmd** [comment]
Changes looks good. needs to be tested once

**Comment by mcjaeger** [comment]
(from discussion) let do next steps in a saparate effort:

**Comment by shaheemazmalmmd** [comment]
Updating text from CSV file leads to duplicate obligation. 

steps to reproduce: 
1) Create obligations for any two licenses using add obligation.
2) Export obligations in CSV.
3) Now edit obligation text that is "full text" for both the licenses.
4) Import the same using import functionality.
5) Now check the obligations "edited" obligations appeared twice.

**Comment by deveaud-m** [comment]
@shaheemazmalmmd Thanks for testing and reporting the issue. 

That's right, the current implementation allows two obligations with the same `topic` to coexist in the DB only if the obligation texts differ. This might be needed to associate one identical obligation topic with different licenses and texts. 

From my point of view the feature is implemented correctly but we can still discuss if obligation topics should be unique in the DB.

**Comment by mcjaeger** [comment]
just checked with the "users": title could be the same. At some point we could have an id displayed somewhere, but from my side I think it could be Ok for now.

**Comment by deveaud-m** [comment]
Thanks @mcjaeger for the clarification.
@shaheemazmalmmd could you please merge those changes?

I'm currently working on #845 in a separate branch.

**Pull request merged**
