### PR TITLE
feat(api): New endpoints to get/delete/restore/update scancode copyright, email, author, url findings

### LINKED ISSUE #2491: Copyright Browser
Aggregated Copyrights, ECC, IPRA, Email/url/Author and Keyword with count, content, activated (FOSSology, Scancode, User) + Operations: edit, delete

### PR DESCRIPTION
**Pull request by dvjsharma**
## Description

This PR adds new endpoints to get/delete/restore/update/ scancode copyright, email, author, url findings via API.

### Changes

1. Added the following new endpoints for scancode copyright findings.
  - GET `uploads/{id}/item/{itemId}/scancode-copyrights` : To retrieve scancode copyright findings.
  - DELETE `uploads/{id}/item/{itemId}/scancode-copyrights/{hash}` : To deactivate scancode copyright.
  - PATCH `uploads/{id}/item/{itemId}/scancode-copyrights/{hash}` : To restore deactivated scancode copyright.
  - PUT `uploads/{id}/item/{itemId}/scancode-copyrights/{hash}` : To update scancode copyright. 

2. Added the following new endpoints for scancode email findings.
  - GET `uploads/{id}/item/{itemId}/scancode-emails` : To retrieve scancode email findings.
  - DELETE `uploads/{id}/item/{itemId}/scancode-emails/{hash}` : To deactivate scancode email.
  - PATCH `uploads/{id}/item/{itemId}/scancode-emails/{hash}` : To restore deactivated scancode email.
  - PUT `uploads/{id}/item/{itemId}/scancode-emails/{hash}` : To update scancode email. 
 
3. Added the following new endpoints for scancode url findings.
  - GET `uploads/{id}/item/{itemId}/scancode-urls` : To retrieve scancode url findings.
  - DELETE `uploads/{id}/item/{itemId}/scancode-urls/{hash}` : To deactivate scancode url.
  - PATCH `uploads/{id}/item/{itemId}/scancode-urls/{hash}` : To restore deactivated scancode url.
  - PUT `uploads/{id}/item/{itemId}/scancode-urls/{hash}` : To update scancode url.
 
4. Added the following new endpoints for scancode author findings.
  - GET `uploads/{id}/item/{itemId}/scancode-authors` : To retrieve scancode author findings.
  - DELETE `uploads/{id}/item/{itemId}/scancode-authors/{hash}` : To deactivate scancode author.
  - PATCH `uploads/{id}/item/{itemId}/scancode-authors/{hash}` : To restore deactivated scancode author.
  - PUT `uploads/{id}/item/{itemId}/scancode-authors/{hash}` : To update scancode author.

5. Enhanced controllers, DAOs, and plugins with new methods and adjustments.
6. Updated the `openapi.yaml` & `openapiv2.yaml` files to have the new API's documentation.

## Test & Screenshots

Make a `GET` request to the endpoint: `uploads/{id}/item/{itemId}/scancode-copyrights`.

image

Make a `DELETE` request to the endpoint: `uploads/{id}/item/{itemId}/scancode-copyrights/{hash}`.

image

Make a `PATCH` request to the endpoint: `uploads/{id}/item/{itemId}/scancode-copyrights/{hash}`.

image

Make a `PUT` request to the endpoint: `uploads/{id}/item/{itemId}/scancode-copyrights/{hash}`.

image

_In the similar way, `email`, `url` and `author` endpoints can also be tested._

Tracked by #2491 
closes #2491 

CC @GMishx @shaheemazmalmmd @dushimsam @soham4abc

### CODE REVIEW

**Comment by dvjsharma** [comment]
NOTE: Made changes on top of #2717. Only review commit [fc8f16d](https://github.com/fossology/fossology/pull/2772/commits/fc8f16dfcd3facae4f344cf1c69370636111f382). Will rebase post #2717 merge.

**Comment by soham4abc** [comment]
@dvjsharma  Can you please squash you commits into a single commit?

**Comment by dvjsharma** [comment]
Hey @soham4abc. As mentioned in previous comment, commits are on top of another PR. Will squash once that is merged. Please consider last comment for review.

**Comment by dvjsharma** [comment]
Since #2717 is merged, rebased with latest master.

**Review by GMishx — APPROVED** [review]
Changes looks good.

**Review by GMishx — APPROVED** [review]
Tested, working as expected.

**Pull request merged**
