### PR TITLE
chore(travis): Add PHP syntax checking to Travis

### LINKED ISSUE #795: Syntax error in Autoload.php
Syntax error found on master, which has been there for a few years:

```
$ find . -name \*.php -type f | xargs -L1 php -l | egrep -v '^No syntax errors detected in'

Parse error: parse error, expecting `')'' in ./src/nomos/agent_tests/testdata/NomosTestfiles/GPL/Autoload.php on line 31
Errors parsing ./src/nomos/agent_tests/testdata/NomosTestfiles/GPL/Autoload.php
```

This is an array declaration with a trailing comma and no `)` character. Is this file used anymore? Has the file been truncated at some point?

It might be worth running `php -l` on all php files as part of the build to pick up these errors.

### PR DESCRIPTION
**Pull request by timurphy**
Fixes #795. A few syntax errors have also been fixed as part of this PR:
 - Autoload.php
 - bitcoin.php
 - fossologyTest.php

Also fixed some typos in testing/README

### CODE REVIEW

**Comment by timurphy** [comment]
More issues detected by Travis, running a slightly different environment to mine:

```
PHP Deprecated:  Assigning the return value of new by reference is deprecated in ./testing/templates/simpletest/myrun.php on line 42

PHP Deprecated:  Assigning the return value of new by reference is deprecated in ./testing/templates/simpletest/runtemplate.php on line 47

PHP Deprecated:  Assigning the return value of new by reference is deprecated in ./testing/functional/runTestCleanup.php on line 42

PHP Deprecated:  Assigning the return value of new by reference is deprecated in ./testing/lib/fossologyTest.php on line 115

PHP Deprecated:  Assigning the return value of new by reference is deprecated in ./testing/utils/upload1File.php on line 56

PHP Deprecated:  Assigning the return value of new by reference is deprecated in ./testing/utils/uploadTestData.php on line 55

PHP Deprecated:  Assigning the return value of new by reference is deprecated in ./testing/utils/fo-runTests.php on line 148

PHP Strict standards:  Static function A::method() should not be abstract in ./vendor/phpunit/php-token-stream/Tests/_files/source2.php on line 5

PHP Fatal error:  Cannot declare class Symfony\Component\DependencyInjection\Dump\Container because the name is already in use in ./vendor/symfony/dependency-injection/Symfony/Component/DependencyInjection/Tests/Fixtures/php/services1-1.php on line 19

PHP Deprecated:  Assigning the return value of new by reference is deprecated in ./cli/tests/all_tests.php on line 33

PHP Deprecated:  Assigning the return value of new by reference is deprecated in ./www/ui_tests/SiteTests/runSiteTests.php on line 44

PHP Deprecated:  Assigning the return value of new by reference is deprecated in ./www/ui_tests/SiteTests/login.php on line 39

PHP Deprecated:  Assigning the return value of new by reference is deprecated in ./www/ui_tests/SiteTests/SearchMenuTest.php on line 42

PHP Deprecated:  Assigning the return value of new by reference is deprecated in ./www/ui_tests/Tweb.php on line 31

PHP Deprecated:  Assigning the return value of new by reference is deprecated in ./www/ui_tests/BasicTests/runBasicTests.php on line 40

PHP Deprecated:  Assigning the return value of new by reference is deprecated in ./www/ui_tests/VerifyTests/runVerifyTests.php on line 40

Syntax errors detected:

Deprecated: Assigning the return value of new by reference is deprecated in ./testing/templates/simpletest/myrun.php on line 42

Deprecated: Assigning the return value of new by reference is deprecated in ./testing/templates/simpletest/runtemplate.php on line 47

Deprecated: Assigning the return value of new by reference is deprecated in ./testing/functional/runTestCleanup.php on line 42

Deprecated: Assigning the return value of new by reference is deprecated in ./testing/lib/fossologyTest.php on line 115

Deprecated: Assigning the return value of new by reference is deprecated in ./testing/utils/upload1File.php on line 56

Deprecated: Assigning the return value of new by reference is deprecated in ./testing/utils/uploadTestData.php on line 55

Deprecated: Assigning the return value of new by reference is deprecated in ./testing/utils/fo-runTests.php on line 148

Strict standards: Static function A::method() should not be abstract in ./vendor/phpunit/php-token-stream/Tests/_files/source2.php on line 5

Fatal error: Cannot declare class Symfony\Component\DependencyInjection\Dump\Container because the name is already in use in ./vendor/symfony/dependency-injection/Symfony/Component/DependencyInjection/Tests/Fixtures/php/services1-1.php on line 19

Errors parsing ./vendor/symfony/dependency-injection/Symfony/Component/DependencyInjection/Tests/Fixtures/php/services1-1.php

Deprecated: Assigning the return value of new by reference is deprecated in ./cli/tests/all_tests.php on line 33

Deprecated: Assigning the return value of new by reference is deprecated in ./www/ui_tests/SiteTests/runSiteTests.php on line 44

Deprecated: Assigning the return value of new by reference is deprecated in ./www/ui_tests/SiteTests/login.php on line 39

Deprecated: Assigning the return value of new by reference is deprecated in ./www/ui_tests/SiteTests/SearchMenuTest.php on line 42

Deprecated: Assigning the return value of new by reference is deprecated in ./www/ui_tests/Tweb.php on line 31

Deprecated: Assigning the return value of new by reference is deprecated in ./www/ui_tests/BasicTests/runBasicTests.php on line 40

Deprecated: Assigning the return value of new by reference is deprecated in ./www/ui_tests/VerifyTests/runVerifyTests.php on line 40
```

**Comment by timurphy** [comment]
Build is passing now for PHP 5. These errors came up for PHP 7 (test files again):

```
Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; KTLDAPBaseAuthenticationProvider has a deprecated constructor in ./nomos/agent_tests/testdata/NomosTestfiles/UnclassifiedLicense/ldapbaseauthenticationprovider.inc.php on line 30

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; KTLDAPBaseAuthenticator has a deprecated constructor in ./nomos/agent_tests/testdata/NomosTestfiles/UnclassifiedLicense/ldapbaseauthenticationprovider.inc.php on line 566
```

**Comment by timurphy** [comment]
I've tweaked the test files to be PHP7 compliant. All tests are passing now.

**Comment by max-wittig** [comment]
Awesome contributions, but could you please also squash(rebase) your commits and use the <a href="https://github.com/fossology/fossology/blob/master/CONTRIBUTING.md#user-content-git-commit-conventions">Conventional Changelog</a>

**Comment by timurphy** [comment]
Done. Travis is failing with this error, unrelated to my change. I think I've seen this before.

```
Step 16 : RUN /usr/local/lib/fossology/fo-postinstall         --agent         --scheduler-only

 ---> Running in 284269b7f215

/usr/local/lib/fossology/fo-postinstall: /usr/local/lib/fossology/fo_dbcheck.php: /usr/bin/php: bad interpreter: Text file busy

FATAL: unable to connect to database, please check /usr/local/etc/fossology/Db.conf

ERROR: Service 'fossology-scheduler' failed to build: The command '/bin/sh -c /usr/local/lib/fossology/fo-postinstall         --agent         --scheduler-only' returned a non-zero code: 1
```

**Comment by max-wittig** [comment]
That's weird and it only happens with the docker-compose setup

**Pull request merged**
