### PR TITLE
feat(packaging): updating existing debian packaging for current fossology

### PR DESCRIPTION
**Pull request by mcjaeger**
updating the debian packaging scripts from taggart@debian.org to
support  recent changes (agents) of the fossology code base. updated
readme text still missing, the existing one is still from 2008.

Usage (one possibility):
* go into project root dir
* `vagrant up` (will use a trusty64 box by default)
* `vagrant ssh`
* `cd /vagrant`
* `sudo dpkg-buildpackage -I`
* see that some dependencies are missing
* `sudo apt-get install debhelper postgresql-server-dev-all libjson0-dev`
* `sudo dpkg-buildpackage -I`
collect the packages (unfortunately at root dir) and test with a trusty64 installation

### CODE REVIEW

**Comment by maximilianhuber** [comment]
I have tried this but have still problems with `/tmp/composer/composer`

<pre>
$ vagrant up
$ <b>vagrant reload</b> # the system was restarted
$ vagrant ssh
<b>vagrant</b> $ cd /vagrant
<b>vagrant</b> $ sudo apt-get install debhelper postgresql-server-dev-all libjson0-dev
<b>vagrant</b> $ sudo dpkg-buildpackage -I
[...]
/usr/bin/install -D -m 644 VERSION /vagrant/debian/fossology-common/usr/share/fossology/maintagent/VERSION
/usr/bin/install -D -m 644 maintagent.conf /vagrant/debian/fossology-common/usr/share/fossology/maintagent/maintagent.conf
mkdir -p /vagrant/debian/fossology-common/etc/fossology/mods-enabled
if test ! -e /vagrant/debian/fossology-common/etc/fossology/mods-enabled/maintagent; then \
		ln -s /usr/share/fossology/maintagent /vagrant/debian/fossology-common/etc/fossology/mods-enabled; \
	fi
make[1]: Leaving directory `/vagrant/src/maintagent'
/usr/bin/make DESTDIR=/vagrant/debian/fossology-common \
           PREFIX=/usr SYSCONFDIR=/etc/fossology LOCALSTATEDIR=/var \
           -C src composer_install
make[1]: Entering directory `/vagrant/src'
current dir: '/vagrant/src'
/usr/bin/install -D -m 644 composer.json composer.lock /vagrant/debian/fossology-common/usr/share/fossology
(cd /vagrant/debian/fossology-common/usr/share/fossology; /tmp/composer/composer install -q --no-dev)
<b>/bin/sh: 1: /tmp/composer/composer: not found</b>
make[1]: *** [composer_install] Error 127
make[1]: Leaving directory `/vagrant/src'
make: *** [install-arch] Error 2
dpkg-buildpackage: error: debian/rules binary gave error exit status 2
</pre>

**Comment by mcjaeger** [comment]
super strange, the vagrant environments should be the same for every one, but the error must be in the differences between the locally shared (project) folders. I will try to do this with clean checkout on a vanilla virtual machine and then report.

**Comment by maximilianhuber** [comment]
I will also have a look. Maybe merge https://github.com/fossology/fossology/pull/738 first?

**Comment by mcjaeger** [comment]
I retested it with a clean checkout (=no clutter from potentially uncommitted files) and it works as expected for me.

I was also wondering: how did executing the vagrant machine script actually work and installing the fossology from (shared vagrant folder containing) source, if the composer is not installed, or if the composer installation does not work? - that should fail in your case, regardless if you want to trigger the package build?

May it be that you were trying the vagrant file from `pbconf` (which is currently centos7 based) while I was just working on the plain vagrant file we have in the project root folder?

Actually the vagrant file in pbconf is for project builder (see the script in side) while the vagrant file in project root is just a plain way to install fossology from source, which was all I needed to execute the debhelper based backage build.

attached the complete dump of this run, to see where I am doing what, switching to the virtual machine in line 23282.

[fossology-debian-package-build-log.txt](https://github.com/fossology/fossology/files/809316/fossology-debian-package-build-log.txt)

**Comment by maximilianhuber** [comment]
I have also retested. The problem was caused by https://github.com/fossology/fossology/pull/701 and does not appear if one do not restart.

Installation also works well.

**Pull request merged**
